Repository eclipse-syson/syson, pull requests merged in 2024-10, with the labels that each got.

#752 [releng] Bump version to 2024.9.1
  backend/application/pom.xml
  backend/application/syson-application-configuration/pom.xml
  backend/application/syson-application/Dockerfile
  backend/application/syson-application/pom.xml
  backend/application/syson-frontend/pom.xml
  backend/application/syson-sysml-export/pom.xml
  backend/application/syson-sysml-import/pom.xml
  backend/metamodel/pom.xml
  backend/metamodel/syson-siriusweb-customnodes-metamodel-edit/pom.xml
  backend/metamodel/syson-siriusweb-customnodes-metamodel/pom.xml
  backend/metamodel/syson-sysml-metamodel-edit/pom.xml
  backend/metamodel/syson-sysml-metamodel/pom.xml
  backend/services/pom.xml
  backend/services/syson-services/pom.xml
  backend/tests/pom.xml
  backend/tests/syson-tests/pom.xml
  backend/views/pom.xml
  backend/views/syson-diagram-actionflow-view/pom.xml
  backend/views/syson-diagram-common-view/pom.xml
  backend/views/syson-diagram-general-view/pom.xml
  backend/views/syson-diagram-interconnection-view/pom.xml
  backend/views/syson-diagram-statetransition-view/pom.xml
  backend/views/syson-diagram-tests/pom.xml
  doc/content/antora.yml
  docker-compose.yml
  frontend/syson-components/package.json
  frontend/syson/package.json
  frontend/syson/src/extensions/SysONFooter.tsx
  integration-tests/package-lock.json
  integration-tests/package.json
  package-lock.json
  package.json
  pom.xml
Labels: pr: to review soon, priority: high

#758 [enh] Add a pull request template
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/build.yml
  .github/workflows/pull-request.yml
Labels: pr: to review soon, priority: high

#759 [test] Update Cypress tests
  integration-tests/cypress/e2e/project/diagrams/general-view/directEditTests.cy.ts
  integration-tests/cypress/e2e/project/diagrams/general-view/dropFromExplorer.cy.ts
  integration-tests/cypress/e2e/project/diagrams/general-view/nodeCreationTests.cy.ts
Labels: pr: to review soon, priority: high

#757 [756] Add short name in container and compartment item labels
  CHANGELOG.adoc
  backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/helper/LabelConstants.java
  backend/services/syson-services/src/main/java/org/eclipse/syson/services/LabelService.java
  backend/services/syson-services/src/main/java/org/eclipse/syson/services/MultiLineLabelSwitch.java
  backend/services/syson-services/src/test/java/org/eclipse/syson/services/LabelServiceTest.java
  backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewLabelService.java
  backend/views/syson-diagram-common-view/src/test/java/org/eclipse/syson/diagram/common/view/services/ViewLabelServiceTest.java
  doc/content/modules/user-manual/pages/release-notes/2024.11.0.adoc
Labels: pr: to review soon, priority: high

#762 [760] Allow to set short name via direct edit
  CHANGELOG.adoc
  backend/services/syson-services/src/main/generated/org/eclipse/syson/services/grammars/DirectEdit.interp
  backend/services/syson-services/src/main/generated/org/eclipse/syson/services/grammars/DirectEditBaseListener.java
  backend/services/syson-services/src/main/generated/org/eclipse/syson/services/grammars/DirectEditListener.java
  backend/services/syson-services/src/main/generated/org/eclipse/syson/services/grammars/DirectEditParser.java
  backend/services/syson-services/src/main/java/org/eclipse/syson/services/DiagramDirectEditListener.java
  backend/services/syson-services/src/main/java/org/eclipse/syson/services/LabelService.java
  backend/services/syson-services/src/main/resources/DirectEdit.g4
  backend/services/syson-services/src/test/java/org/eclipse/syson/services/DiagramDirectEditListenerTest.java
  doc/content/modules/user-manual/pages/hands-on/how-tos/model-management.adoc
  doc/content/modules/user-manual/pages/release-notes/2024.11.0.adoc
Labels: pr: to review soon, priority: high

#763 [761] Make Declared Short Name accessible from the Core tab
  CHANGELOG.adoc
  backend/application/syson-application-configuration/pom.xml
  backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/services/CoreFeaturesSwitch.java
  backend/application/syson-application-configuration/src/test/java/org/eclipse/syson/application/services/DetailsViewServiceTest.java
  doc/content/modules/user-manual/pages/release-notes/2024.11.0.adoc
Labels: pr: to review soon, priority: high

#766 [765] Remove default name of relationships and improve edge labels
  CHANGELOG.adoc
  backend/services/syson-services/src/main/java/org/eclipse/syson/services/ElementInitializerSwitch.java
  backend/services/syson-services/src/main/java/org/eclipse/syson/services/LabelService.java
  backend/services/syson-services/src/main/java/org/eclipse/syson/services/MultiLineLabelSwitch.java
  backend/views/syson-diagram-actionflow-view/src/test/java/org/eclipse/syson/diagram/actionflow/view/ActionFlowViewDiagramDescriptionTests.java
  backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/edges/AbstractAllocateEdgeDescriptionProvider.java
  backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/edges/AbstractDependencyEdgeDescriptionProvider.java
  backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/edges/AbstractSuccessionEdgeDescriptionProvider.java
  backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewCreateService.java
  backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewLabelService.java
  backend/views/syson-diagram-common-view/src/test/java/org/eclipse/syson/diagram/common/view/services/ViewLabelServiceTest.java
  backend/views/syson-diagram-general-view/src/test/java/org/eclipse/syson/diagram/general/view/GeneralViewDiagramDescriptionTests.java
  backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/edges/BindingConnectorAsUsageEdgeDescriptionProvider.java
  backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/services/InterconnectionViewCreateService.java
  backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/services/InterconnectionViewLabelService.java
  backend/views/syson-diagram-interconnection-view/src/test/java/org/eclipse/syson/diagram/interconnection/view/InterconnectionViewDiagramDescriptionTests.java
  backend/views/syson-diagram-statetransition-view/src/test/java/org/eclipse/syson/diagram/statetransition/view/StateTransitionViewDiagramDescriptionTests.java
  doc/content/modules/user-manual/pages/release-notes/2024.11.0.adoc
Labels: pr: to review soon, priority: high

#769 [767] Allow to create dependencies in the explorer
  CHANGELOG.adoc
  backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/services/GetChildCreationSwitch.java
  backend/application/syson-application-configuration/src/test/java/org/eclipse/syson/application/services/GetChildCreationSwitchTest.java
  doc/content/modules/user-manual/pages/release-notes/2024.11.0.adoc
Labels: pr: to review soon, priority: high

#772 [771] Allow the drop of elements on empty diagram nodes
  CHANGELOG.adoc
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controller/editingContext/checkers/SemanticCheckerService.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/checkers/CheckNodeOnDiagram.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVDropFromExplorerTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVEdgeCreationTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeActionFlowCreationTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeAnalysisCreationTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeExtensionCreationTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeInterconnectionCreationTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeRequirementCreationTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeStateTransitionCreationTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeStructureCreationTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeTemporalCreationTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVTopNodeCreationTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/testers/DropFromExplorerTester.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/metamodel/helper/ImplicitSpecializationsTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/services/SemanticRunnableFactory.java
  backend/views/syson-diagram-actionflow-view/src/main/java/org/eclipse/syson/diagram/actionflow/view/nodes/ActionFlowViewEmptyDiagramNodeDescriptionProvider.java
  backend/views/syson-diagram-actionflow-view/src/test/java/org/eclipse/syson/diagram/actionflow/view/ActionFlowViewDiagramDescriptionTests.java
  backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/AbstractEmptyDiagramNodeDescriptionProvider.java
  backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewToolService.java
  backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/GeneralViewEmptyDiagramNodeDescriptionProvider.java
  backend/views/syson-diagram-general-view/src/test/java/org/eclipse/syson/diagram/general/view/GeneralViewDiagramDescriptionTests.java
  backend/views/syson-diagram-interconnection-view/src/test/java/org/eclipse/syson/diagram/interconnection/view/InterconnectionViewDiagramDescriptionTests.java
  backend/views/syson-diagram-statetransition-view/src/main/java/org/eclipse/syson/diagram/statetransition/view/nodes/StateTransitionViewEmptyDiagramNodeDescriptionProvider.java
  backend/views/syson-diagram-statetransition-view/src/test/java/org/eclipse/syson/diagram/statetransition/view/StateTransitionViewDiagramDescriptionTests.java
  backend/views/syson-diagram-tests/pom.xml
  backend/views/syson-diagram-tests/src/main/java/org/eclipse/syson/diagram/tests/checkers/DiagramDescriptionHasNoEmptyDiagramNodeChecker.java
  backend/views/syson-diagram-tests/src/main/java/org/eclipse/syson/diagram/tests/checkers/DiagramDescriptionHasOneEmptyDiagramNodeChecker.java
  doc/content/modules/user-manual/pages/release-notes/2024.11.0.adoc
Labels: pr: to review soon, priority: high

#776 [775] Exclude src/test/resources from checkstyle
  CHANGELOG.adoc
  backend/application/syson-application-configuration/.checkstyle
  backend/application/syson-application/.checkstyle
  backend/application/syson-sysml-export/.checkstyle
  backend/application/syson-sysml-import/.checkstyle
  backend/metamodel/syson-siriusweb-customnodes-metamodel-edit/.checkstyle
  backend/metamodel/syson-siriusweb-customnodes-metamodel/.checkstyle
  backend/metamodel/syson-sysml-metamodel-edit/.checkstyle
  backend/metamodel/syson-sysml-metamodel/.checkstyle
  backend/services/syson-services/.checkstyle
  backend/tests/syson-tests/.checkstyle
  backend/views/syson-diagram-actionflow-view/.checkstyle
  backend/views/syson-diagram-common-view/.checkstyle
  backend/views/syson-diagram-general-view/.checkstyle
  backend/views/syson-diagram-interconnection-view/.checkstyle
  backend/views/syson-diagram-statetransition-view/.checkstyle
  backend/views/syson-diagram-tests/.checkstyle
  doc/content/modules/user-manual/pages/release-notes/2024.11.0.adoc
Labels: pr: to review later, priority: low

#778 [releng] Switch to Sirius Web 2024.9.8
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.adoc
  backend/application/syson-application-configuration/pom.xml
  backend/application/syson-application/pom.xml
  backend/application/syson-sysml-export/pom.xml
  backend/application/syson-sysml-import/pom.xml
  backend/metamodel/syson-siriusweb-customnodes-metamodel-edit/pom.xml
  backend/metamodel/syson-siriusweb-customnodes-metamodel/pom.xml
  backend/services/syson-services/pom.xml
  backend/views/syson-diagram-actionflow-view/pom.xml
  backend/views/syson-diagram-common-view/pom.xml
  backend/views/syson-diagram-general-view/pom.xml
  backend/views/syson-diagram-interconnection-view/pom.xml
  backend/views/syson-diagram-statetransition-view/pom.xml
  backend/views/syson-diagram-tests/pom.xml
  doc/content/modules/user-manual/pages/release-notes/2024.11.0.adoc
  frontend/syson-components/package.json
  frontend/syson/package.json
  package-lock.json
Labels: pr: to review soon, priority: high

#781 [779] Add new tool to create a full subsetting from Part Usage
  CHANGELOG.adoc
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVAddNewSubsettingFromPartUsageTests.java
  backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewCreateService.java
  backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/tools/PartUsageSubsettingNodeToolProvider.java
  backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/services/GeneralViewNodeToolSectionSwitch.java
  doc/content/modules/user-manual/pages/release-notes/2024.11.0.adoc
Labels: pr: to review soon, priority: high

#786 [777] Handle boolean attributes recognized as string by the import parser.
  CHANGELOG.adoc
  backend/application/syson-sysml-import/src/main/java/org/eclipse/syson/sysml/parser/AstObjectParser.java
  backend/application/syson-sysml-import/src/test/java/org/eclipse/syson/sysml/ASTTransformerTest.java
  backend/application/syson-sysml-import/src/test/resources/ASTTransformerTest/convertBooleanTest/model.ast.json
  backend/application/syson-sysml-import/src/test/resources/ASTTransformerTest/convertBooleanTest/model.sysml
  doc/content/modules/user-manual/pages/release-notes/2024.11.0.adoc
Labels: pr: to review soon, priority: high

#788 [785] Add New Binding Connector As Usage tool on PartUsage in Interconnection view
  CHANGELOG.adoc
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/interconnection/view/IVAddNewBindingConnectorAsUsageFromPartUsageTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/data/SysMLv2Identifiers.java
  backend/application/syson-application/src/test/resources/scripts/syson-test-database.sql
  backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewCreateService.java
  backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/ILeveledNodeDescriptionNameGenerator.java
  backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/IVDescriptionNameGenerator.java
  backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/nodes/ChildUsageNodeDescriptionProvider.java
  backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/nodes/FirstLevelChildUsageNodeDescriptionProvider.java
  backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/services/ChildUsageCreationNodeToolsProvider.java
  backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/services/FirstLevelChildUsageCreationNodeToolsProvider.java
  backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/services/ILeveledCreationNodeToolsProvider.java
  backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/services/InterconnectionViewCreateService.java
  backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/services/InterconnectionViewNodeToolSectionSwitch.java
  backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/tools/PartUsageBindingConnectorAsUsageNodeToolProvider.java
  doc/content/modules/user-manual/pages/release-notes/2024.11.0.adoc
Labels: pr: to review soon, priority: high

#793 [790] Add New Interface tool on PartUsage in IV
  CHANGELOG.adoc
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/interconnection/view/IVAddNewInterfaceFromPartUsageTests.java
  backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/services/ChildUsageCreationNodeToolsProvider.java
  backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/services/FirstLevelChildUsageCreationNodeToolsProvider.java
  backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/services/InterconnectionViewCreateService.java
  backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/tools/PartUsageInterfaceNodeToolProvider.java
  doc/content/modules/user-manual/pages/release-notes/2024.11.0.adoc
Labels: pr: to review soon, priority: high

#798 [releng] Switch to java-uuid-generator 5.1.0
  CHANGELOG.adoc
  backend/metamodel/syson-sysml-metamodel/pom.xml
  doc/content/modules/user-manual/pages/release-notes/2024.11.0.adoc
Labels: pr: to review soon, priority: high

#801 [795] Fix name resolution of implicit redefining feature
  CHANGELOG.adoc
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/export/ImportExportTests.java
  backend/application/syson-sysml-export/src/main/java/org/eclipse/syson/sysml/export/utils/NameDeresolver.java
  backend/application/syson-sysml-export/src/test/java/org/eclipse/syson/sysml/export/SysMLElementSerializerTest.java
  backend/application/syson-sysml-export/src/test/java/org/eclipse/syson/sysml/export/models/UseCaseDefinitionTestModel.java
  backend/application/syson-sysml-export/src/test/java/org/eclipse/syson/sysml/export/utils/NameDeresolverTest.java
  backend/application/syson-sysml-import/src/main/java/org/eclipse/syson/sysml/parser/ProxyResolver.java
  backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/helper/DeresolvingNamespaceProvider.java
  backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/NamespaceImpl.java
  doc/content/modules/user-manual/pages/release-notes/2024.11.0.adoc
Labels: pr: to review soon, priority: high

#814 [releng] Add code coverage check on backend
  .github/workflows/build.yml
  backend/application/syson-application-configuration/pom.xml
  backend/application/syson-sysml-export/pom.xml
  backend/application/syson-sysml-import/pom.xml
  backend/metamodel/syson-siriusweb-customnodes-metamodel-edit/pom.xml
  backend/metamodel/syson-siriusweb-customnodes-metamodel/pom.xml
  backend/metamodel/syson-sysml-metamodel-edit/pom.xml
  backend/metamodel/syson-sysml-metamodel/pom.xml
  backend/releng/pom.xml
  backend/releng/syson-test-coverage/.project
  backend/releng/syson-test-coverage/pom.xml
  backend/services/syson-direct-edit-grammar/pom.xml
  backend/services/syson-services/pom.xml
  backend/views/syson-diagram-actionflow-view/pom.xml
  backend/views/syson-diagram-common-view/pom.xml
  backend/views/syson-diagram-general-view/pom.xml
  backend/views/syson-diagram-interconnection-view/pom.xml
  backend/views/syson-diagram-statetransition-view/pom.xml
  pom.xml
  scripts/check-coverage.jsh
Labels: pr: to review soon, priority: high

#816 [releng] Update github actions versions in workflows
  .github/workflows/build.yml
  .github/workflows/doc-gen.yml
  .github/workflows/pull-request.yml
Labels: pr: to review soon, priority: high

#813 [812] Fixing import visibility in Deresolver
  CHANGELOG.adoc
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/export/ImportExportTests.java
  backend/application/syson-sysml-export/src/main/java/org/eclipse/syson/sysml/export/utils/NameDeresolver.java
  backend/application/syson-sysml-export/src/test/java/org/eclipse/syson/sysml/export/utils/NameDeresolverTest.java
  doc/content/modules/user-manual/pages/release-notes/2024.11.0.adoc
  integration-tests/cypress/e2e/project/explorer/insertTextualSysMLv2Tests.cy.ts
Labels: pr: to review later, priority: high
