Repository eclipse-syson/syson, pull requests merged in 2025-01, with the labels that each got.

#931 [doc] Fix content and linter issues in installation guide
  doc/content/modules/installation-guide/pages/how-tos/https.adoc
  doc/content/modules/installation-guide/pages/how-tos/install.adoc
  doc/content/modules/installation-guide/pages/how-tos/install/ecosystem_only.adoc
  doc/content/modules/installation-guide/pages/how-tos/install/local_test.adoc
  doc/content/modules/installation-guide/pages/how-tos/install/multi_user_test.adoc
  doc/content/modules/installation-guide/pages/how-tos/install/production_deploy.adoc
Labels: priority: low, type: documentation

#932 [doc] Fix content of the user manual cycle page
  doc/content/modules/user-manual/pages/cycle.adoc
Labels: priority: low, type: documentation

#928 [899] Add support for ConcernUsage in diagram 'General View'
  CHANGELOG.adoc
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeRequirementCreationTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeStructureCreationTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVTopNodeCreationTests.java
  backend/application/syson-application/src/test/resources/scripts/syson-test-database.sql
  backend/services/syson-services/src/main/java/org/eclipse/syson/services/MultiLineLabelSwitch.java
  backend/services/syson-services/src/test/java/org/eclipse/syson/services/MultilineLabelSwitchTest.java
  backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/GeneralViewDiagramDescriptionProvider.java
  backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/FakeNodeDescriptionProvider.java
  backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/GeneralViewNodeDescriptionProviderSwitch.java
  backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/RequirementUsageActorsCompartmentNodeDescriptionProvider.java
  backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/RequirementUsageSubjectCompartmentNodeDescriptionProvider.java
  doc/content/modules/user-manual/assets/images/release-notes-gv-concern-usage.png
  doc/content/modules/user-manual/pages/release-notes/2025.2.0.adoc
Labels: pr: to review later, priority: low

#942 [941] Prevent edition of imported user libraries from the details view
  CHANGELOG.adoc
  backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/services/DetailsViewService.java
  backend/application/syson-application-configuration/src/test/java/org/eclipse/syson/application/services/DetailsViewServiceTest.java
  doc/content/modules/user-manual/pages/release-notes/2025.2.0.adoc
Labels: pr: to review soon, priority: high

#954 [953] Fix server crash when successive REST APIs calls are executed
  CHANGELOG.adoc
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/rest/RestControllerIntegrationTests.java
  backend/services/syson-sysml-rest-api-services/pom.xml
  backend/services/syson-sysml-rest-api-services/src/main/java/org/eclipse/syson/sysml/rest/api/SysMLv2SerializerConfig.java
  doc/content/modules/user-manual/pages/release-notes/2025.2.0.adoc
Labels: pr: to review soon, priority: high

#962 [961] Add valid default names for Elements
  CHANGELOG.adoc
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVAddNewFeatureTypingFromPartUsageTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeRequirementCreationTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/interconnection/view/IVAddNewBindingConnectorAsUsageFromPartUsageTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/interconnection/view/IVAddNewFlowConnectionFromPartUsageTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/interconnection/view/IVAddNewInterfaceFromPartUsageTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/testers/NodeCreationTester.java
  backend/services/syson-services/src/main/java/org/eclipse/syson/services/ElementInitializerSwitch.java
  backend/services/syson-services/src/test/java/org/eclipse/syson/services/ElementInitializerSwitchTest.java
  backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewCreateService.java
  backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/services/InterconnectionViewCreateService.java
  backend/views/syson-diagram-interconnection-view/src/test/java/org/eclipse/syson/diagram/interconnection/view/InterconnectionViewCreateServiceTests.java
  doc/content/modules/user-manual/pages/release-notes/2025.2.0.adoc
  integration-tests/cypress/e2e/project/details/details.cy.ts
  integration-tests/cypress/e2e/project/diagrams/diagramCreationTests.cy.ts
  integration-tests/cypress/e2e/project/explorer/semanticElementCreationTests.cy.ts
  integration-tests/cypress/workbench/Explorer.ts
Labels: pr: to review soon, priority: high

#966 [releng] Switch to Sirius Web 2025.1.1
  .github/workflows/build.yml
  CHANGELOG.adoc
  backend/application/syson-application-configuration/pom.xml
  backend/application/syson-application/pom.xml
  backend/application/syson-frontend/pom.xml
  backend/application/syson-sysml-export/pom.xml
  backend/application/syson-sysml-import/pom.xml
  backend/metamodel/syson-siriusweb-customnodes-metamodel-edit/pom.xml
  backend/metamodel/syson-siriusweb-customnodes-metamodel/pom.xml
  backend/metamodel/syson-sysml-metamodel-edit/pom.xml
  backend/metamodel/syson-sysml-metamodel/pom.xml
  backend/releng/syson-test-coverage/pom.xml
  backend/services/syson-direct-edit-grammar/pom.xml
  backend/services/syson-services/pom.xml
  backend/services/syson-sysml-rest-api-services/pom.xml
  backend/tests/syson-tests/pom.xml
  backend/views/syson-diagram-actionflow-view/pom.xml
  backend/views/syson-diagram-common-view/pom.xml
  backend/views/syson-diagram-general-view/pom.xml
  backend/views/syson-diagram-interconnection-view/pom.xml
  backend/views/syson-diagram-statetransition-view/pom.xml
  backend/views/syson-diagram-tests/pom.xml
  backend/views/syson-tree-explorer-view/pom.xml
  doc/content/modules/user-manual/assets/images/release-notes-query-view-getObjectById.png
  doc/content/modules/user-manual/assets/images/release-notes-query-view-ownedMember.png
  doc/content/modules/user-manual/assets/images/release-notes-query-view.png
  doc/content/modules/user-manual/pages/release-notes/2025.2.0.adoc
  frontend/syson-components/package.json
  frontend/syson/package.json
  frontend/syson/src/theme/sysonTheme.ts
  package-lock.json
  package.json
  turbo.json
Labels: pr: to review soon, priority: high

#967 [fix] Fix swagger APIs update with Sirius Web 2025.1.1
  backend/services/syson-sysml-rest-api-services/src/main/java/org/eclipse/syson/sysml/rest/api/SysMLv2SerializerConfig.java
  doc/content/modules/user-manual/assets/attachments/sirius-web-openapi.json
  doc/content/modules/user-manual/pages/release-notes/2025.2.0.adoc
Labels: pr: to review soon, priority: high

#968 [releng] Bump version to 2025.1.1
  backend/application/pom.xml
  backend/application/syson-application-configuration/pom.xml
  backend/application/syson-application/pom.xml
  backend/application/syson-frontend/pom.xml
  backend/application/syson-sysml-export/pom.xml
  backend/application/syson-sysml-import/pom.xml
  backend/metamodel/pom.xml
  backend/metamodel/syson-siriusweb-customnodes-metamodel-edit/pom.xml
  backend/metamodel/syson-siriusweb-customnodes-metamodel/pom.xml
  backend/metamodel/syson-sysml-metamodel-edit/pom.xml
  backend/metamodel/syson-sysml-metamodel/pom.xml
  backend/releng/pom.xml
  backend/releng/syson-test-coverage/pom.xml
  backend/services/pom.xml
  backend/services/syson-direct-edit-grammar/pom.xml
  backend/services/syson-services/pom.xml
  backend/services/syson-sysml-rest-api-services/pom.xml
  backend/tests/pom.xml
  backend/tests/syson-tests/pom.xml
  backend/views/pom.xml
  backend/views/syson-diagram-actionflow-view/pom.xml
  backend/views/syson-diagram-common-view/pom.xml
  backend/views/syson-diagram-general-view/pom.xml
  backend/views/syson-diagram-interconnection-view/pom.xml
  backend/views/syson-diagram-statetransition-view/pom.xml
  backend/views/syson-diagram-tests/pom.xml
  backend/views/syson-tree-explorer-view/pom.xml
  doc/content/antora.yml
  doc/content/modules/user-manual/pages/release-notes/2025.2.0.adoc
  docker-compose.yml
  frontend/syson-components/package.json
  frontend/syson/package.json
  frontend/syson/src/extensions/SysONFooter.tsx
  integration-tests/package-lock.json
  integration-tests/package.json
  package-lock.json
  package.json
  pom.xml
Labels: pr: to review soon, priority: high

#969 [releng] Prepare next release
  docker-compose.yml
Labels: pr: to review soon, priority: high

#970 [releng] Switch to Sirius Web 2025.1.2
  CHANGELOG.adoc
  backend/application/syson-application-configuration/pom.xml
  backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/configuration/SysMLEditingContextProcessor.java
  backend/application/syson-application/pom.xml
  backend/application/syson-sysml-export/pom.xml
  backend/application/syson-sysml-import/pom.xml
  backend/metamodel/syson-siriusweb-customnodes-metamodel-edit/pom.xml
  backend/metamodel/syson-siriusweb-customnodes-metamodel/pom.xml
  backend/services/syson-direct-edit-grammar/pom.xml
  backend/services/syson-services/pom.xml
  backend/services/syson-sysml-rest-api-services/pom.xml
  backend/views/syson-diagram-actionflow-view/pom.xml
  backend/views/syson-diagram-common-view/pom.xml
  backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewCreateService.java
  backend/views/syson-diagram-general-view/pom.xml
  backend/views/syson-diagram-interconnection-view/pom.xml
  backend/views/syson-diagram-statetransition-view/pom.xml
  backend/views/syson-diagram-tests/pom.xml
  backend/views/syson-tree-explorer-view/pom.xml
  backend/views/syson-tree-explorer-view/src/main/java/org/eclipse/syson/tree/explorer/view/SysONExplorerContributionProvider.java
  backend/views/syson-tree-explorer-view/src/main/java/org/eclipse/syson/tree/explorer/view/services/SysONDefaultExplorerServices.java
  doc/content/modules/user-manual/assets/attachments/sirius-web-openapi.json
  doc/content/modules/user-manual/assets/images/release-notes-diagrams-export-as-png.png
  doc/content/modules/user-manual/pages/release-notes/2025.2.0.adoc
  frontend/syson-components/package.json
  frontend/syson/package.json
  package-lock.json
Labels: pr: to review soon, priority: high

#971 [releng] Bump version to 2025.1.2
  backend/application/pom.xml
  backend/application/syson-application-configuration/pom.xml
  backend/application/syson-application/pom.xml
  backend/application/syson-frontend/pom.xml
  backend/application/syson-sysml-export/pom.xml
  backend/application/syson-sysml-import/pom.xml
  backend/metamodel/pom.xml
  backend/metamodel/syson-siriusweb-customnodes-metamodel-edit/pom.xml
  backend/metamodel/syson-siriusweb-customnodes-metamodel/pom.xml
  backend/metamodel/syson-sysml-metamodel-edit/pom.xml
  backend/metamodel/syson-sysml-metamodel/pom.xml
  backend/releng/pom.xml
  backend/releng/syson-test-coverage/pom.xml
  backend/services/pom.xml
  backend/services/syson-direct-edit-grammar/pom.xml
  backend/services/syson-services/pom.xml
  backend/services/syson-sysml-rest-api-services/pom.xml
  backend/tests/pom.xml
  backend/tests/syson-tests/pom.xml
  backend/views/pom.xml
  backend/views/syson-diagram-actionflow-view/pom.xml
  backend/views/syson-diagram-common-view/pom.xml
  backend/views/syson-diagram-general-view/pom.xml
  backend/views/syson-diagram-interconnection-view/pom.xml
  backend/views/syson-diagram-statetransition-view/pom.xml
  backend/views/syson-diagram-tests/pom.xml
  backend/views/syson-tree-explorer-view/pom.xml
  doc/content/antora.yml
  docker-compose.yml
  frontend/syson-components/package.json
  frontend/syson/package.json
  frontend/syson/src/extensions/SysONFooter.tsx
  integration-tests/package-lock.json
  integration-tests/package.json
  package-lock.json
  package.json
  pom.xml
Labels: pr: to review soon, priority: high

#979 [doc] Contribute new question in FAQ about the project name
  doc/content/modules/user-manual/pages/faq/faq.adoc
Labels: priority: low, type: documentation

#978 [977] Add SysMLv2 validation rules
  CHANGELOG.adoc
  backend/application/pom.xml
  backend/application/syson-application/pom.xml
  backend/application/syson-application/src/test/java/org/eclipse/syson/AbstractIntegrationTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/objects/ObjectRestControllerIntegrationTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/projects/ProjectDataVersioningRestControllerIntegrationTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/rest/RestControllerIntegrationTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/data/SysMLv2Identifiers.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/validation/ValidationRulesTests.java
  backend/application/syson-sysml-validation/.checkstyle
  backend/application/syson-sysml-validation/.classpath
  backend/application/syson-sysml-validation/.project
  backend/application/syson-sysml-validation/.settings/org.eclipse.core.resources.prefs
  backend/application/syson-sysml-validation/.settings/org.eclipse.core.runtime.prefs
  backend/application/syson-sysml-validation/.settings/org.eclipse.jdt.apt.core.prefs
  backend/application/syson-sysml-validation/.settings/org.eclipse.jdt.core.prefs
  backend/application/syson-sysml-validation/.settings/org.eclipse.jdt.ui.prefs
  backend/application/syson-sysml-validation/.settings/org.eclipse.m2e.core.prefs
  backend/application/syson-sysml-validation/.settings/org.springframework.ide.eclipse.boot.prefs
  backend/application/syson-sysml-validation/.settings/org.springframework.ide.eclipse.prefs
  backend/application/syson-sysml-validation/pom.xml
  backend/application/syson-sysml-validation/src/main/java/org/eclipse/syson/sysml/validation/SysMLv2ValidationRules.java
  backend/application/syson-sysml-validation/src/main/java/org/eclipse/syson/sysml/validation/SysMLv2ValidationService.java
  backend/application/syson-sysml-validation/src/main/java/org/eclipse/syson/sysml/validation/SysMLv2Validator.java
  backend/application/syson-sysml-validation/src/main/java/org/eclipse/syson/sysml/validation/SysMLv2ValidatorConfiguration.java
  backend/application/syson-sysml-validation/src/main/java/org/eclipse/syson/sysml/validation/SysONQueryServices.java
  backend/application/syson-sysml-validation/src/main/java/org/eclipse/syson/sysml/validation/ValidationRule.java
  backend/application/syson-sysml-validation/src/main/resources/.gitkeep
  backend/application/syson-sysml-validation/src/test/java/.gitkeep
  backend/releng/syson-test-coverage/pom.xml
  doc/content/modules/user-manual/pages/release-notes/2025.2.0.adoc
  scripts/check-coverage.jsh
Labels: pr: to review soon, priority: high
