Repository eclipse-syson/syson, pull requests merged in 2025-06, with the labels that each got.

#1340 [1339] Make Details view more extensible to determine read-only-ness
  CHANGELOG.adoc
  backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/configuration/SysMLv2PropertiesConfigurer.java
  backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/services/DetailsViewService.java
  backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/services/SysONReadOnlyObjectPredicateDelegate.java
  backend/application/syson-application-configuration/src/test/java/org/eclipse/syson/application/services/DetailsViewServiceTest.java
  doc/content/modules/user-manual/pages/release-notes/2025.6.0.adoc
Labels: pr: to review soon, priority: high

#1348 [1346] Improve DirectEdit grammar on ConstraintUsage
  CHANGELOG.adoc
  backend/services/syson-direct-edit-grammar/src/main/java/org/eclipse/syson/services/grammars/DirectEdit.interp
  backend/services/syson-direct-edit-grammar/src/main/java/org/eclipse/syson/services/grammars/DirectEdit.tokens
  backend/services/syson-direct-edit-grammar/src/main/java/org/eclipse/syson/services/grammars/DirectEditBaseListener.java
  backend/services/syson-direct-edit-grammar/src/main/java/org/eclipse/syson/services/grammars/DirectEditLexer.interp
  backend/services/syson-direct-edit-grammar/src/main/java/org/eclipse/syson/services/grammars/DirectEditLexer.java
  backend/services/syson-direct-edit-grammar/src/main/java/org/eclipse/syson/services/grammars/DirectEditLexer.tokens
  backend/services/syson-direct-edit-grammar/src/main/java/org/eclipse/syson/services/grammars/DirectEditListener.java
  backend/services/syson-direct-edit-grammar/src/main/java/org/eclipse/syson/services/grammars/DirectEditParser.java
  backend/services/syson-direct-edit-grammar/src/main/resources/DirectEdit.g4
  backend/services/syson-services/src/main/java/org/eclipse/syson/services/DiagramDirectEditListener.java
  backend/services/syson-services/src/main/java/org/eclipse/syson/services/LabelService.java
  backend/services/syson-services/src/main/java/org/eclipse/syson/util/NamedProxy.java
  backend/services/syson-services/src/test/java/org/eclipse/syson/services/DiagramDirectEditListenerTest.java
  backend/services/syson-services/src/test/java/org/eclipse/syson/services/data/SmallFlashlightExample.java
  doc/content/modules/user-manual/pages/release-notes/2025.6.0.adoc
Labels: pr: to review soon, priority: high

#1349 [releng] Bump version to 2025.4.7
  backend/application/pom.xml
  backend/application/syson-application-configuration/pom.xml
  backend/application/syson-application/pom.xml
  backend/application/syson-frontend/pom.xml
  backend/application/syson-sysml-export/pom.xml
  backend/application/syson-sysml-import/pom.xml
  backend/application/syson-sysml-validation/pom.xml
  backend/metamodel/pom.xml
  backend/metamodel/syson-siriusweb-customnodes-metamodel-edit/pom.xml
  backend/metamodel/syson-siriusweb-customnodes-metamodel/pom.xml
  backend/metamodel/syson-sysml-metamodel-edit/pom.xml
  backend/metamodel/syson-sysml-metamodel/pom.xml
  backend/releng/pom.xml
  backend/releng/syson-test-coverage/pom.xml
  backend/services/pom.xml
  backend/services/syson-direct-edit-grammar/pom.xml
  backend/services/syson-services/pom.xml
  backend/services/syson-sysml-rest-api-services/pom.xml
  backend/tests/pom.xml
  backend/tests/syson-tests/pom.xml
  backend/views/pom.xml
  backend/views/syson-diagram-actionflow-view/pom.xml
  backend/views/syson-diagram-common-view/pom.xml
  backend/views/syson-diagram-general-view/pom.xml
  backend/views/syson-diagram-interconnection-view/pom.xml
  backend/views/syson-diagram-statetransition-view/pom.xml
  backend/views/syson-diagram-tests/pom.xml
  backend/views/syson-tree-explorer-view/pom.xml
  doc/content/antora.yml
  doc/content/modules/developer-guide/assets/attachments/sirius-web-openapi.json
  docker-compose.yml
  frontend/syson-components/package.json
  frontend/syson/package.json
  integration-tests/package-lock.json
  integration-tests/package.json
  package-lock.json
  package.json
  pom.xml
Labels: pr: to review soon, priority: high

#1353 [releng] Switch to Sirius Web 2025.4.8
  CHANGELOG.adoc
  backend/application/syson-application-configuration/pom.xml
  backend/application/syson-application/pom.xml
  backend/application/syson-sysml-export/pom.xml
  backend/application/syson-sysml-import/pom.xml
  backend/application/syson-sysml-validation/pom.xml
  backend/metamodel/syson-siriusweb-customnodes-metamodel-edit/pom.xml
  backend/metamodel/syson-siriusweb-customnodes-metamodel/pom.xml
  backend/services/syson-direct-edit-grammar/pom.xml
  backend/services/syson-services/pom.xml
  backend/services/syson-sysml-rest-api-services/pom.xml
  backend/views/syson-diagram-actionflow-view/pom.xml
  backend/views/syson-diagram-common-view/pom.xml
  backend/views/syson-diagram-general-view/pom.xml
  backend/views/syson-diagram-interconnection-view/pom.xml
  backend/views/syson-diagram-statetransition-view/pom.xml
  backend/views/syson-diagram-tests/pom.xml
  backend/views/syson-tree-explorer-view/pom.xml
  doc/content/modules/user-manual/pages/release-notes/2025.6.0.adoc
  frontend/syson-components/package.json
  frontend/syson-components/src/nodes/imported_package/SysMLImportedPackageNodeConverter.ts
  frontend/syson-components/src/nodes/note/SysMLNoteNodeConverter.ts
  frontend/syson-components/src/nodes/package/SysMLPackageNodeConverter.ts
  frontend/syson-components/src/nodes/view_frame/SysMLViewFrameNodeConverter.ts
  frontend/syson/package.json
  package-lock.json
Labels: pr: to review soon, priority: high

#1341 [1336] Add manage visibility node action in General View
  CHANGELOG.adoc
  backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/services/GeneralViewManageVisibilityNodeActionProvider.java
  doc/content/modules/user-manual/assets/images/release-notes-manage-visibility.png
  doc/content/modules/user-manual/pages/release-notes/2025.6.0.adoc
Labels: pr: to review soon, priority: high

#1360 [1359] Handle textual export of ViewUsage
  CHANGELOG.adoc
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/export/ImportExportTests.java
  backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/textual/SysMLElementSerializer.java
  doc/content/modules/user-manual/pages/release-notes/2025.6.0.adoc
Labels: pr: to review soon, priority: high

#1362 [1350] Improve DirectEdit tool on Feature to be able to edit basic
  CHANGELOG.adoc
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVAnnotatingElementTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVItemAndAttributeExpressionTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVStateTransitionUsageTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/testers/DirectEditInitialLabelTester.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/testers/DirectEditTester.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/data/GeneralViewItemAndAttributeProjectData.java
  backend/application/syson-application/src/test/resources/scripts/database-content/GeneralView-ItemAndAttributesModelTest.sql
  backend/application/syson-sysml-export/src/main/java/org/eclipse/syson/sysml/export/SysMLv2DocumentExporter.java
  backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/helper/DeresolvingNamespaceProvider.java
  backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/textual/SysMLElementSerializer.java
  backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/textual/utils/FileNameDeresolver.java
  backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/textual/utils/INameDeresolver.java
  backend/metamodel/syson-sysml-metamodel/src/test/java/org/eclipse/syson/sysml/textual/FileNameDeresolverTest.java
  backend/metamodel/syson-sysml-metamodel/src/test/java/org/eclipse/syson/sysml/textual/SysMLElementSerializerTest.java
  backend/services/syson-direct-edit-grammar/src/main/java/org/eclipse/syson/services/grammars/DirectEdit.interp
  backend/services/syson-direct-edit-grammar/src/main/java/org/eclipse/syson/services/grammars/DirectEditBaseListener.java
  backend/services/syson-direct-edit-grammar/src/main/java/org/eclipse/syson/services/grammars/DirectEditListener.java
  backend/services/syson-direct-edit-grammar/src/main/java/org/eclipse/syson/services/grammars/DirectEditParser.java
  backend/services/syson-direct-edit-grammar/src/main/resources/DirectEdit.g4
  backend/services/syson-services/pom.xml
  backend/services/syson-services/src/main/java/org/eclipse/syson/services/DiagramDirectEditListener.java
  backend/services/syson-services/src/main/java/org/eclipse/syson/services/LabelService.java
  backend/services/syson-services/src/main/java/org/eclipse/syson/services/MultiLineLabelSwitch.java
  backend/services/syson-services/src/main/java/org/eclipse/syson/services/SimpleNameDeresolver.java
  backend/services/syson-services/src/test/java/org/eclipse/syson/services/DiagramDirectEditListenerTest.java
  backend/services/syson-services/src/test/java/org/eclipse/syson/services/data/ItemAndAttributesModelTest.java
  backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewLabelService.java
  doc/content/modules/user-manual/pages/release-notes/2025.6.0.adoc
Labels: pr: to review soon, priority: high

#1365 [fix] Create a General View diagram when a ViewUsage is created
  backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/services/SysMLv2EditService.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controller/explorer/view/SysONExplorerTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controller/objects/ObjectCreationTests.java
  backend/views/syson-tree-explorer-view/src/main/java/org/eclipse/syson/tree/explorer/view/menu/context/CreateRepresentationInputProcessor.java
  backend/views/syson-tree-explorer-view/src/main/java/org/eclipse/syson/tree/explorer/view/menu/context/SysONExplorerTreeItemContextMenuEntryProvider.java
  doc/content/modules/user-manual/pages/release-notes/2025.6.0.adoc
Labels: pr: to review soon, priority: high

#1366 [fix] Improve Expose labels in Explorer view
  backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/services/SysMLv2LabelService.java
  backend/metamodel/syson-sysml-metamodel-edit/src/main/java/org/eclipse/syson/sysml/provider/MembershipExposeItemProvider.java
  backend/metamodel/syson-sysml-metamodel-edit/src/main/java/org/eclipse/syson/sysml/provider/NamespaceExposeItemProvider.java
Labels: pr: to review soon, priority: high

#1364 [1363] Add a menu action that will hide children that don't have chil…
  CHANGELOG.adoc
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVManageVisibilityTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/data/GeneralViewManageVisibilityTestsProjectData.java
  backend/application/syson-application/src/test/resources/scripts/database-content/GeneralView-ManageVisibility.sql
  backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/services/nodeactions/managevisibility/GeneralViewManageVisibilityNodeActionProvider.java
  backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/services/nodeactions/managevisibility/GeneralViewManageVisibilityRevealValuedContentAction.java
  backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/services/nodeactions/managevisibility/GeneralViewManageVisibilityRevealValuedContentHandler.java
  doc/content/modules/user-manual/pages/release-notes/2025.6.0.adoc
Labels: pr: to review soon, priority: high

#1369 [releng] Switch to Sirius Web 2025.4.9
  CHANGELOG.adoc
  backend/application/syson-application-configuration/pom.xml
  backend/application/syson-application/pom.xml
  backend/application/syson-sysml-export/pom.xml
  backend/application/syson-sysml-import/pom.xml
  backend/application/syson-sysml-validation/pom.xml
  backend/metamodel/syson-siriusweb-customnodes-metamodel-edit/pom.xml
  backend/metamodel/syson-siriusweb-customnodes-metamodel/pom.xml
  backend/services/syson-direct-edit-grammar/pom.xml
  backend/services/syson-services/pom.xml
  backend/services/syson-sysml-rest-api-services/pom.xml
  backend/views/syson-diagram-actionflow-view/pom.xml
  backend/views/syson-diagram-common-view/pom.xml
  backend/views/syson-diagram-general-view/pom.xml
  backend/views/syson-diagram-interconnection-view/pom.xml
  backend/views/syson-diagram-statetransition-view/pom.xml
  backend/views/syson-diagram-tests/pom.xml
  backend/views/syson-tree-explorer-view/pom.xml
  doc/content/modules/user-manual/pages/release-notes/2025.6.0.adoc
  frontend/syson-components/package.json
  frontend/syson/package.json
  package-lock.json
Labels: pr: to review soon, priority: high

#1372 [doc] Update release note
  doc/content/modules/user-manual/assets/images/appearance_custom_applied.png
  doc/content/modules/user-manual/assets/images/appearance_tool_section.png
  doc/content/modules/user-manual/assets/images/view-usage-graphical-contents.png
  doc/content/modules/user-manual/assets/images/view-usage-nodes.png
  doc/content/modules/user-manual/pages/release-notes/2025.6.0.adoc
Labels: pr: to review soon, priority: high

#1370 [1368] Add an edge representation for FeatureValue linking two Features
  CHANGELOG.adoc
  backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/configuration/SysMLv2PropertiesConfigurer.java
  backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/services/DetailsViewService.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVItemAndAttributeExpressionTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/testers/DeleteFromDiagramRunner.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/testers/DeleteFromDiagramTester.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/testers/DirectEditTester.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/data/GeneralViewItemAndAttributeProjectData.java
  backend/application/syson-application/src/test/resources/scripts/database-content/GeneralView-ItemAndAttributesModelTest.sql
  backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/FeatureValueImpl.java
  backend/services/syson-services/src/main/java/org/eclipse/syson/util/SysONEContentAdapter.java
  backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/edges/AbstractFeatureValueEdgeDescriptionProvider.java
  backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewEdgeService.java
  backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewLabelService.java
  backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/GeneralViewDiagramDescriptionProvider.java
  backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/edges/FeatureValueEdgeDescriptionProvider.java
  backend/views/syson-diagram-general-view/src/test/java/org/eclipse/syson/diagram/general/view/GeneralViewDiagramDescriptionTests.java
  doc/content/modules/user-manual/assets/images/FeatureValueDetailView.png
  doc/content/modules/user-manual/assets/images/FeatureValueEdge.png
  doc/content/modules/user-manual/pages/release-notes/2025.6.0.adoc
Labels: pr: to review soon, priority: high

#1374 [releng] Bump version to 2025.4.9
  backend/application/pom.xml
  backend/application/syson-application-configuration/pom.xml
  backend/application/syson-application/pom.xml
  backend/application/syson-frontend/pom.xml
  backend/application/syson-sysml-export/pom.xml
  backend/application/syson-sysml-import/pom.xml
  backend/application/syson-sysml-validation/pom.xml
  backend/metamodel/pom.xml
  backend/metamodel/syson-siriusweb-customnodes-metamodel-edit/pom.xml
  backend/metamodel/syson-siriusweb-customnodes-metamodel/pom.xml
  backend/metamodel/syson-sysml-metamodel-edit/pom.xml
  backend/metamodel/syson-sysml-metamodel/pom.xml
  backend/releng/pom.xml
  backend/releng/syson-test-coverage/pom.xml
  backend/services/pom.xml
  backend/services/syson-direct-edit-grammar/pom.xml
  backend/services/syson-services/pom.xml
  backend/services/syson-sysml-rest-api-services/pom.xml
  backend/tests/pom.xml
  backend/tests/syson-tests/pom.xml
  backend/views/pom.xml
  backend/views/syson-diagram-actionflow-view/pom.xml
  backend/views/syson-diagram-common-view/pom.xml
  backend/views/syson-diagram-general-view/pom.xml
  backend/views/syson-diagram-interconnection-view/pom.xml
  backend/views/syson-diagram-statetransition-view/pom.xml
  backend/views/syson-diagram-tests/pom.xml
  backend/views/syson-tree-explorer-view/pom.xml
  doc/content/antora.yml
  docker-compose.yml
  frontend/syson-components/package.json
  frontend/syson/package.json
  integration-tests/package-lock.json
  integration-tests/package.json
  package-lock.json
  package.json
  pom.xml
Labels: pr: to review soon, priority: high

#1375 [doc] Reference Flashlight tutorials in TOC
  doc/content/modules/user-manual/partials/nav-tuto.adoc
  doc/content/modules/user-manual/partials/nav-ui.adoc
Labels: pr: to review soon, priority: low, type: documentation

#1381 [releng] Switch to Sirius Web 2025.6.0
  CHANGELOG.adoc
  backend/application/syson-application-configuration/pom.xml
  backend/application/syson-application/pom.xml
  backend/application/syson-sysml-export/pom.xml
  backend/application/syson-sysml-import/pom.xml
  backend/application/syson-sysml-validation/pom.xml
  backend/metamodel/syson-siriusweb-customnodes-metamodel-edit/pom.xml
  backend/metamodel/syson-siriusweb-customnodes-metamodel/pom.xml
  backend/services/syson-direct-edit-grammar/pom.xml
  backend/services/syson-services/pom.xml
  backend/services/syson-sysml-rest-api-services/pom.xml
  backend/views/syson-diagram-actionflow-view/pom.xml
  backend/views/syson-diagram-common-view/pom.xml
  backend/views/syson-diagram-general-view/pom.xml
  backend/views/syson-diagram-interconnection-view/pom.xml
  backend/views/syson-diagram-statetransition-view/pom.xml
  backend/views/syson-diagram-tests/pom.xml
  backend/views/syson-tree-explorer-view/pom.xml
  doc/content/modules/developer-guide/assets/attachments/sirius-web-openapi.json
  doc/content/modules/user-manual/pages/release-notes/2025.6.0.adoc
  frontend/syson-components/package.json
  frontend/syson/package.json
  package-lock.json
Labels: pr: to review soon, priority: high

#1382 [releng] Bump version to 2025.6.0
  backend/application/pom.xml
  backend/application/syson-application-configuration/pom.xml
  backend/application/syson-application/pom.xml
  backend/application/syson-frontend/pom.xml
  backend/application/syson-sysml-export/pom.xml
  backend/application/syson-sysml-import/pom.xml
  backend/application/syson-sysml-validation/pom.xml
  backend/metamodel/pom.xml
  backend/metamodel/syson-siriusweb-customnodes-metamodel-edit/pom.xml
  backend/metamodel/syson-siriusweb-customnodes-metamodel/pom.xml
  backend/metamodel/syson-sysml-metamodel-edit/pom.xml
  backend/metamodel/syson-sysml-metamodel/pom.xml
  backend/releng/pom.xml
  backend/releng/syson-test-coverage/pom.xml
  backend/services/pom.xml
  backend/services/syson-direct-edit-grammar/pom.xml
  backend/services/syson-services/pom.xml
  backend/services/syson-sysml-rest-api-services/pom.xml
  backend/tests/pom.xml
  backend/tests/syson-tests/pom.xml
  backend/views/pom.xml
  backend/views/syson-diagram-actionflow-view/pom.xml
  backend/views/syson-diagram-common-view/pom.xml
  backend/views/syson-diagram-general-view/pom.xml
  backend/views/syson-diagram-interconnection-view/pom.xml
  backend/views/syson-diagram-statetransition-view/pom.xml
  backend/views/syson-diagram-tests/pom.xml
  backend/views/syson-tree-explorer-view/pom.xml
  doc/content/antora.yml
  docker-compose.yml
  frontend/syson-components/package.json
  frontend/syson/package.json
  integration-tests/package-lock.json
  integration-tests/package.json
  package-lock.json
  package.json
  pom.xml
Labels: pr: to review soon, priority: high

#1386 [1385] Update SysIDE dependency to 0.9.0
  CHANGELOG.adoc
  backend/application/syson-sysml-import/src/main/resources/syside-cli.js
  doc/content/modules/user-manual/pages/release-notes/2025.8.0.adoc
Labels: pr: to review soon, priority: high

#1388 [releng] Switch to Sirius Web 2025.6.1
  CHANGELOG.adoc
  backend/application/syson-application-configuration/pom.xml
  backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/configuration/SysMLv2PropertiesConfigurer.java
  backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/services/DetailsViewService.java
  backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/services/SysMLv2EditService.java
  backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/services/SysMLv2LabelService.java
  backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/services/SysONReadOnlyObjectPredicateDelegate.java
  backend/application/syson-application-configuration/src/test/java/org/eclipse/syson/application/services/DetailsViewServiceTest.java
  backend/application/syson-application-configuration/src/test/java/org/eclipse/syson/application/services/SysONReadOnlyObjectPredicateDelegateTests.java
  backend/application/syson-application/pom.xml
  backend/application/syson-frontend/pom.xml
  backend/application/syson-sysml-export/pom.xml
  backend/application/syson-sysml-import/pom.xml
  backend/application/syson-sysml-validation/pom.xml
  backend/metamodel/syson-siriusweb-customnodes-metamodel-edit/pom.xml
  backend/metamodel/syson-siriusweb-customnodes-metamodel/pom.xml
  backend/metamodel/syson-sysml-metamodel-edit/pom.xml
  backend/metamodel/syson-sysml-metamodel/pom.xml
  backend/releng/syson-test-coverage/pom.xml
  backend/services/syson-direct-edit-grammar/pom.xml
  backend/services/syson-services/pom.xml
  backend/services/syson-sysml-rest-api-services/pom.xml
  backend/tests/syson-tests/pom.xml
  backend/views/syson-diagram-actionflow-view/pom.xml
  backend/views/syson-diagram-common-view/pom.xml
  backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/AbstractPackageNodeDescriptionProvider.java
  backend/views/syson-diagram-general-view/pom.xml
  backend/views/syson-diagram-interconnection-view/pom.xml
  backend/views/syson-diagram-statetransition-view/pom.xml
  backend/views/syson-diagram-tests/pom.xml
  backend/views/syson-tree-explorer-view/pom.xml
  backend/views/syson-tree-explorer-view/src/main/java/org/eclipse/syson/tree/explorer/view/handlers/DropTreeItemHandler.java
  backend/views/syson-tree-explorer-view/src/main/java/org/eclipse/syson/tree/explorer/view/services/SysONDefaultExplorerServices.java
  backend/views/syson-tree-explorer-view/src/main/java/org/eclipse/syson/tree/explorer/view/services/SysONExplorerLabelService.java
  backend/views/syson-tree-explorer-view/src/test/java/org/eclipse/syson/tree/explorer/view/services/SysONDefaultExplorerServicesTest.java
  doc/content/modules/user-manual/pages/release-notes/2025.8.0.adoc
  frontend/syson-components/package.json
  frontend/syson/package.json
  package-lock.json
  package.json
  scripts/check-coverage.jsh
Labels: pr: to review soon, priority: high

#1389 [enh] Update security file
  SECURITY.adoc
  SECURITY.md
Labels: pr: to review soon, priority: high

#1390 [releng] Update all workflow actions
  .github/workflows/build.yml
  .github/workflows/doc-gen.yml
  .github/workflows/generate-maven-sbom.yml
  .github/workflows/generate-npm-sbom.yml
  .github/workflows/pull-request.yml
Labels: pr: to review soon, priority: high

#1391 [releng] Avoid template-injection in github workflows
  .github/workflows/build.yml
  .github/workflows/doc-gen.yml
  .github/workflows/generate-maven-sbom.yml
  .github/workflows/generate-npm-sbom.yml
Labels: pr: to review soon, priority: high

#1005 [893] Fix Expand All tool in SysON Explorer View
  CHANGELOG.adoc
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controller/explorer/testers/TreeItemContextMenuTester.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controller/explorer/view/SysONExplorerTests.java
  backend/views/syson-tree-explorer-view/src/main/java/org/eclipse/syson/tree/explorer/view/SysONExplorerTreeDescriptionProvider.java
  backend/views/syson-tree-explorer-view/src/main/java/org/eclipse/syson/tree/explorer/view/fragments/KerMLStandardLibraryDirectory.java
  backend/views/syson-tree-explorer-view/src/main/java/org/eclipse/syson/tree/explorer/view/fragments/LibrariesDirectory.java
  backend/views/syson-tree-explorer-view/src/main/java/org/eclipse/syson/tree/explorer/view/fragments/SysMLStandardLibraryDirectory.java
  backend/views/syson-tree-explorer-view/src/main/java/org/eclipse/syson/tree/explorer/view/fragments/UserLibrariesDirectory.java
  backend/views/syson-tree-explorer-view/src/main/java/org/eclipse/syson/tree/explorer/view/menu/context/SysONExplorerTreeItemContextMenuEntryProvider.java
  backend/views/syson-tree-explorer-view/src/main/java/org/eclipse/syson/tree/explorer/view/services/ComposedSysONExplorerService.java
  backend/views/syson-tree-explorer-view/src/main/java/org/eclipse/syson/tree/explorer/view/services/SysONDefaultExplorerServices.java
  backend/views/syson-tree-explorer-view/src/main/java/org/eclipse/syson/tree/explorer/view/services/api/ISysONDefaultExplorerService.java
  backend/views/syson-tree-explorer-view/src/main/java/org/eclipse/syson/tree/explorer/view/services/api/ISysONExplorerFragment.java
  backend/views/syson-tree-explorer-view/src/main/java/org/eclipse/syson/tree/explorer/view/services/api/ISysONExplorerService.java
  backend/views/syson-tree-explorer-view/src/main/java/org/eclipse/syson/tree/explorer/view/services/api/ISysONExplorerServiceDelegate.java
  doc/content/modules/user-manual/pages/release-notes/2025.8.0.adoc
  frontend/syson/src/index.tsx
Labels: pr: to review later, priority: low

#1401 [1398] Fix exposed Element update while d'n'd Element on General View
  CHANGELOG.adoc
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVDropFromExplorerTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/data/GeneralViewAddExistingElementsTestProjectData.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/tree/explorer/view/handlers/DropTreeItemHandlerTest.java
  backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewToolService.java
  doc/content/modules/user-manual/pages/release-notes/2025.8.0.adoc
Labels: pr: to review soon, priority: high

#1410 [releng] Switch to Sirius Web 2025.6.2
  CHANGELOG.adoc
  backend/application/syson-application-configuration/pom.xml
  backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/migration/DiagramOnViewUsageMigrationParticipant.java
  backend/application/syson-application/pom.xml
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controller/explorer/view/SysONExplorerTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controller/relatedelements/view/RelatedElementsViewTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/details/view/DetailsViewControllerIntegrationTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeRequirementCreationTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVTopNodeCreationTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/validation/ValidationRulesTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/services/diagrams/GivenDiagramSubscription.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/tree/explorer/view/handlers/DropTreeItemHandlerTest.java
  backend/application/syson-sysml-export/pom.xml
  backend/application/syson-sysml-import/pom.xml
  backend/application/syson-sysml-validation/pom.xml
  backend/metamodel/syson-siriusweb-customnodes-metamodel-edit/pom.xml
  backend/metamodel/syson-siriusweb-customnodes-metamodel/pom.xml
  backend/services/syson-direct-edit-grammar/pom.xml
  backend/services/syson-services/pom.xml
  backend/services/syson-sysml-rest-api-services/pom.xml
  backend/views/syson-diagram-actionflow-view/pom.xml
  backend/views/syson-diagram-common-view/pom.xml
  backend/views/syson-diagram-general-view/pom.xml
  backend/views/syson-diagram-interconnection-view/pom.xml
  backend/views/syson-diagram-statetransition-view/pom.xml
  backend/views/syson-diagram-tests/pom.xml
  backend/views/syson-tree-explorer-view/pom.xml
  doc/content/modules/user-manual/pages/release-notes/2025.6.0.adoc
  doc/content/modules/user-manual/pages/release-notes/2025.8.0.adoc
  frontend/syson-components/package.json
  frontend/syson/package.json
  package-lock.json
Labels: pr: to review soon, priority: high

#1412 [1411] Add standard libraries migration participants
  CHANGELOG.adoc
  backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/migration/StandardLibrariesElementsDiagramMigrationParticipant.java
  backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/migration/StandardLibrariesElementsReferencesMigrationParticipant.java
  backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/services/SysONIdentityService.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVAnnotatingElementTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVBorderNodePortCreationTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/data/GeneralViewActionTransitionUsagesProjectData.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/migration/StandardLibrariesIdsMigrationParticipantTest.java
  backend/application/syson-application/src/test/resources/scripts/database-content/StandardLibrariesElementsIdsMigrationParticipant-Test.sql
  backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/tools/AbstractFreeFormCompartmentNodeToolProvider.java
  doc/content/modules/user-manual/pages/release-notes/2025.8.0.adoc
Labels: pr: to review soon, priority: high
