Repository eclipse-syson/syson, pull requests merged in 2025-03, with the labels that each got.

#1026 [1024] Add wrap option on definition and usage node label
  CHANGELOG.adoc
  backend/services/syson-services/src/main/java/org/eclipse/syson/util/ViewConstants.java
  backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/AbstractDefinitionNodeDescriptionProvider.java
  backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/AbstractUsageNodeDescriptionProvider.java
  doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
Labels: pr: to review soon, priority: low

#1073 [releng] Do not launch cypress tests on main branch
  .github/workflows/build.yml
Labels: pr: to review soon, priority: high

#1043 [1042] Improve SuccessionAsUsage defining new the actions
  CHANGELOG.adoc
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/export/ImportExportTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/imports/ImportSysMLModelTest.java
  backend/application/syson-sysml-import/src/main/java/org/eclipse/syson/sysml/ASTTransformer.java
  backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/helper/ImplicitSpecializationSwitch.java
  doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
Labels: pr: to review later, priority: low

#1046 [1045] Improve export to properly handle named SuccessionAsUsage
  CHANGELOG.adoc
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/export/ImportExportTests.java
  backend/application/syson-sysml-export/src/main/java/org/eclipse/syson/sysml/export/SysMLElementSerializer.java
  doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
Labels: pr: to review later, priority: low

#1081 [1080] Improve import and resolution of ConjugatedPort
  CHANGELOG.adoc
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/export/ImportExportTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/imports/ImportSysMLModelTest.java
  backend/application/syson-sysml-import/src/main/java/org/eclipse/syson/sysml/ASTTransformer.java
  backend/application/syson-sysml-import/src/test/java/org/eclipse/syson/sysml/ASTTransformerTest.java
  doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
Labels: pr: to review soon, priority: high

#1082 [870] Fix an issue while computing the name of VariantMembership
  CHANGELOG.adoc
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/export/ImportExportTests.java
  backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/VariantMembershipImpl.java
  backend/metamodel/syson-sysml-metamodel/src/test/java/org/eclipse/syson/sysml/impl/VariantMembershipImplTest.java
  doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
Labels: pr: to review soon, priority: high

#1076 [1075] Fix ClassCastException while importing a model with name conflict
  CHANGELOG.adoc
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/imports/ImportSysMLModelTest.java
  backend/application/syson-sysml-import/src/main/java/org/eclipse/syson/sysml/parser/ProxyResolver.java
  backend/application/syson-sysml-import/src/test/java/org/eclipse/syson/sysml/ASTTransformerTest.java
  backend/application/syson-sysml-import/src/test/resources/ASTTransformerTest/convertConjugatedPortTest/conjugatedPort.ast.json
  backend/application/syson-sysml-import/src/test/resources/ASTTransformerTest/convertConjugatedPortTest/conjugatedPort.sysml
  doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
Labels: pr: to review soon, priority: high

#1092 [1091] Fix qualified names in FeatureReferenceExpression export
  CHANGELOG.adoc
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/export/ImportExportTests.java
  backend/application/syson-sysml-export/src/main/java/org/eclipse/syson/sysml/export/SysMLElementSerializer.java
  doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
Labels: pr: to review soon, priority: high

#1095 [1048] Improve TransitionUsage to improve control of succession of
  CHANGELOG.adoc
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/imports/ImportSysMLModelTest.java
  backend/application/syson-application/src/test/resources/part_changes.json
  backend/application/syson-application/src/test/resources/simple_project.json
  backend/application/syson-application/src/test/resources/simple_project_changes.json
  backend/application/syson-sysml-import/src/main/java/org/eclipse/syson/sysml/ASTTransformer.java
  backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/helper/ImplicitSpecializationSwitch.java
  backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/FeatureImpl.java
  backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/TransitionUsageImpl.java
  doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
Labels: pr: to review soon, priority: high

#1097 [1094] Improve the import of guard on TransitionUsages
  CHANGELOG.adoc
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/imports/ImportSysMLModelTest.java
  backend/application/syson-sysml-import/src/main/java/org/eclipse/syson/sysml/parser/ContainmentReferenceHandler.java
  backend/application/syson-sysml-import/src/main/java/org/eclipse/syson/sysml/parser/translation/EAttributeTranslator.java
  backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/ParameterMembershipImpl.java
  doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
Labels: pr: to review soon, priority: high

#1099 [releng] Switch to Sirius Web 2025.2.2
  CHANGELOG.adoc
  backend/application/syson-application-configuration/pom.xml
  backend/application/syson-application/pom.xml
  backend/application/syson-application/src/test/resources/scripts/cleanup.sql
  backend/application/syson-sysml-export/pom.xml
  backend/application/syson-sysml-import/pom.xml
  backend/application/syson-sysml-validation/pom.xml
  backend/metamodel/syson-siriusweb-customnodes-metamodel-edit/pom.xml
  backend/metamodel/syson-siriusweb-customnodes-metamodel/pom.xml
  backend/services/syson-direct-edit-grammar/pom.xml
  backend/services/syson-services/pom.xml
  backend/services/syson-sysml-rest-api-services/pom.xml
  backend/views/syson-diagram-actionflow-view/pom.xml
  backend/views/syson-diagram-common-view/pom.xml
  backend/views/syson-diagram-general-view/pom.xml
  backend/views/syson-diagram-interconnection-view/pom.xml
  backend/views/syson-diagram-statetransition-view/pom.xml
  backend/views/syson-diagram-tests/pom.xml
  backend/views/syson-tree-explorer-view/pom.xml
  doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
  frontend/syson-components/package.json
  frontend/syson/package.json
  package-lock.json
  package.json
Labels: pr: to review soon, priority: high

#1100 [releng] Bump version to 2025.2.2
  backend/application/pom.xml
  backend/application/syson-application-configuration/pom.xml
  backend/application/syson-application/pom.xml
  backend/application/syson-frontend/pom.xml
  backend/application/syson-sysml-export/pom.xml
  backend/application/syson-sysml-import/pom.xml
  backend/application/syson-sysml-validation/pom.xml
  backend/metamodel/pom.xml
  backend/metamodel/syson-siriusweb-customnodes-metamodel-edit/pom.xml
  backend/metamodel/syson-siriusweb-customnodes-metamodel/pom.xml
  backend/metamodel/syson-sysml-metamodel-edit/pom.xml
  backend/metamodel/syson-sysml-metamodel/pom.xml
  backend/releng/pom.xml
  backend/releng/syson-test-coverage/pom.xml
  backend/services/pom.xml
  backend/services/syson-direct-edit-grammar/pom.xml
  backend/services/syson-services/pom.xml
  backend/services/syson-sysml-rest-api-services/pom.xml
  backend/tests/pom.xml
  backend/tests/syson-tests/pom.xml
  backend/views/pom.xml
  backend/views/syson-diagram-actionflow-view/pom.xml
  backend/views/syson-diagram-common-view/pom.xml
  backend/views/syson-diagram-general-view/pom.xml
  backend/views/syson-diagram-interconnection-view/pom.xml
  backend/views/syson-diagram-statetransition-view/pom.xml
  backend/views/syson-diagram-tests/pom.xml
  backend/views/syson-tree-explorer-view/pom.xml
  doc/content/antora.yml
  docker-compose.yml
  frontend/syson-components/package.json
  frontend/syson/package.json
  integration-tests/package-lock.json
  integration-tests/package.json
  package-lock.json
  package.json
  pom.xml
Labels: pr: to review soon, priority: high

#1071 [1077] Fix explorer in case of non-sysml domain
  CHANGELOG.adoc
  backend/views/syson-tree-explorer-view/src/main/java/org/eclipse/syson/tree/explorer/view/services/SysONDefaultExplorerServices.java
  backend/views/syson-tree-explorer-view/src/test/java/org/eclipse/syson/tree/explorer/view/services/SysONDefaultExplorerServicesTest.java
  doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
  scripts/check-coverage.jsh
Labels: pr: to review soon, priority: high

#1107 [1105] Implement ConnectionDefinition derived references and operations
  CHANGELOG.adoc
  backend/application/syson-application/src/test/resources/part_changes.json
  backend/application/syson-application/src/test/resources/simple_project.json
  backend/application/syson-application/src/test/resources/simple_project_changes.json
  backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/ConnectionDefinitionImpl.java
  backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/ConnectionUsageImpl.java
  backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/ConnectorAsUsageImpl.java
  backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/ConnectorImpl.java
  backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/ItemUsageImpl.java
  backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/NamespaceImpl.java
  backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/PartUsageImpl.java
  backend/metamodel/syson-sysml-metamodel/src/test/java/org/eclipse/syson/sysml/impl/ConnectionDefinitionImplTest.java
  backend/metamodel/syson-sysml-metamodel/src/test/java/org/eclipse/syson/sysml/impl/ConnectionUsageImplTest.java
  doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
Labels: pr: to review soon, priority: high

#1114 [fix] Move publication frontend from syson-components to syson
  frontend/syson-components/package.json
  package-lock.json
  scripts/check-frontend-dependencies.js
Labels: pr: to review soon, priority: high

#1115 [releng] Switch to Sirius Web 2025.2.4
  CHANGELOG.adoc
  backend/application/syson-application-configuration/pom.xml
  backend/application/syson-application/pom.xml
  backend/application/syson-application/src/test/java/org/eclipse/syson/JavaServiceIsCalledChecker.java
  backend/application/syson-sysml-export/pom.xml
  backend/application/syson-sysml-import/pom.xml
  backend/application/syson-sysml-validation/pom.xml
  backend/metamodel/syson-siriusweb-customnodes-metamodel-edit/pom.xml
  backend/metamodel/syson-siriusweb-customnodes-metamodel/pom.xml
  backend/services/syson-direct-edit-grammar/pom.xml
  backend/services/syson-services/pom.xml
  backend/services/syson-sysml-rest-api-services/pom.xml
  backend/services/syson-sysml-rest-api-services/src/main/java/org/eclipse/syson/sysml/rest/api/SysMLv2RestDataVersionPayloadSerializerService.java
  backend/services/syson-sysml-rest-api-services/src/main/java/org/eclipse/syson/sysml/rest/api/SysMLv2SerializerConfig.java
  backend/services/syson-sysml-rest-api-services/src/main/java/org/eclipse/syson/sysml/rest/api/SysONProjectDataVersioningRestService.java
  backend/views/syson-diagram-actionflow-view/pom.xml
  backend/views/syson-diagram-common-view/pom.xml
  backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/edges/AbstractAllocateEdgeDescriptionProvider.java
  backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/edges/AbstractDefinitionOwnedUsageEdgeDescriptionProvider.java
  backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/edges/AbstractDependencyEdgeDescriptionProvider.java
  backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/edges/AbstractFeatureTypingEdgeDescriptionProvider.java
  backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/edges/AbstractRedefinitionEdgeDescriptionProvider.java
  backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/edges/AbstractSubclassificationEdgeDescriptionProvider.java
  backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/edges/AbstractSubsettingEdgeDescriptionProvider.java
  backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/edges/AbstractSuccessionEdgeDescriptionProvider.java
  backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/edges/AbstractUsageNestedUsageEdgeDescriptionProvider.java
  backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/edges/AnnotationEdgeDescriptionProvider.java
  backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/edges/TransitionEdgeDescriptionProvider.java
  backend/views/syson-diagram-general-view/pom.xml
  backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/edges/NestedActorEdgeDescriptionProvider.java
  backend/views/syson-diagram-interconnection-view/pom.xml
  backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/edges/BindingConnectorAsUsageEdgeDescriptionProvider.java
  backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/edges/FlowConnectionUsageEdgeDescriptionProvider.java
  backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/edges/InterfaceUsageEdgeDescriptionProvider.java
  backend/views/syson-diagram-statetransition-view/pom.xml
  backend/views/syson-diagram-tests/pom.xml
  backend/views/syson-tree-explorer-view/pom.xml
  doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
  frontend/syson-components/package.json
  frontend/syson/package.json
  package-lock.json
  scripts/update-sirius-web.js
Labels: pr: to review soon, priority: high

#1116 [releng] Bump version to 2025.2.4
  .github/workflows/generate-maven-sbom.yml
  CHANGELOG.adoc
  backend/application/pom.xml
  backend/application/syson-application-configuration/pom.xml
  backend/application/syson-application/pom.xml
  backend/application/syson-frontend/pom.xml
  backend/application/syson-sysml-export/pom.xml
  backend/application/syson-sysml-import/pom.xml
  backend/application/syson-sysml-validation/pom.xml
  backend/metamodel/pom.xml
  backend/metamodel/syson-siriusweb-customnodes-metamodel-edit/pom.xml
  backend/metamodel/syson-siriusweb-customnodes-metamodel/pom.xml
  backend/metamodel/syson-sysml-metamodel-edit/pom.xml
  backend/metamodel/syson-sysml-metamodel/pom.xml
  backend/releng/pom.xml
  backend/releng/syson-test-coverage/pom.xml
  backend/services/pom.xml
  backend/services/syson-direct-edit-grammar/pom.xml
  backend/services/syson-services/pom.xml
  backend/services/syson-sysml-rest-api-services/pom.xml
  backend/tests/pom.xml
  backend/tests/syson-tests/pom.xml
  backend/views/pom.xml
  backend/views/syson-diagram-actionflow-view/pom.xml
  backend/views/syson-diagram-common-view/pom.xml
  backend/views/syson-diagram-general-view/pom.xml
  backend/views/syson-diagram-interconnection-view/pom.xml
  backend/views/syson-diagram-statetransition-view/pom.xml
  backend/views/syson-diagram-tests/pom.xml
  backend/views/syson-tree-explorer-view/pom.xml
  doc/content/antora.yml
  doc/content/modules/developer-guide/assets/attachments/sirius-web-openapi.json
  docker-compose.yml
  frontend/syson-components/package.json
  frontend/syson/package.json
  integration-tests/package-lock.json
  integration-tests/package.json
  package-lock.json
  package.json
  pom.xml
Labels: pr: to review soon, priority: high

#1123 [1037] "Add existing nested element" tool on the Action Flow compartment
  CHANGELOG.adoc
  backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/ActionFlowCompartmentNodeDescriptionProvider.java
  doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
Labels: pr: to review soon, priority: high

#1128 [1079] Fix an Stackoverflow in the Connector implementation
  backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/ConnectorImpl.java
  backend/metamodel/syson-sysml-metamodel/src/test/java/org/eclipse/syson/sysml/impl/ConnectorImplTest.java
Labels: pr: to review soon, priority: high

#1129 [releng] Switch to Sirius Web 2025.2.5
  CHANGELOG.adoc
  backend/application/syson-application-configuration/pom.xml
  backend/application/syson-application/pom.xml
  backend/application/syson-frontend/pom.xml
  backend/application/syson-sysml-export/pom.xml
  backend/application/syson-sysml-import/pom.xml
  backend/application/syson-sysml-validation/pom.xml
  backend/metamodel/syson-siriusweb-customnodes-metamodel-edit/pom.xml
  backend/metamodel/syson-siriusweb-customnodes-metamodel/pom.xml
  backend/metamodel/syson-sysml-metamodel-edit/pom.xml
  backend/metamodel/syson-sysml-metamodel/pom.xml
  backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/helper/ImplicitSpecializationSwitch.java
  backend/releng/syson-test-coverage/pom.xml
  backend/services/syson-direct-edit-grammar/pom.xml
  backend/services/syson-services/pom.xml
  backend/services/syson-sysml-rest-api-services/pom.xml
  backend/tests/syson-tests/pom.xml
  backend/views/syson-diagram-actionflow-view/pom.xml
  backend/views/syson-diagram-common-view/pom.xml
  backend/views/syson-diagram-general-view/pom.xml
  backend/views/syson-diagram-interconnection-view/pom.xml
  backend/views/syson-diagram-statetransition-view/pom.xml
  backend/views/syson-diagram-tests/pom.xml
  backend/views/syson-tree-explorer-view/pom.xml
  doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
  frontend/syson-components/package.json
  frontend/syson-components/src/nodes/imported_package/SysMLImportedPackageNode.tsx
  frontend/syson-components/src/nodes/note/SysMLNoteNode.tsx
  frontend/syson-components/src/nodes/package/SysMLPackageNode.tsx
  frontend/syson/package.json
  package-lock.json
Labels: pr: to review soon, priority: high

#1136 [1118] Add support for updating version of library dependencies
  CHANGELOG.adoc
  backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/publication/SySONLibraryPublicationHandler.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/libraries/SysONLibraryImportTestServer.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/libraries/imports/SySONLibraryImportByCopyTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/libraries/imports/SySONLibraryImportByReferenceTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/libraries/update/SySONLibraryUpdateTests.java
  backend/views/syson-tree-explorer-view/src/main/java/org/eclipse/syson/tree/explorer/view/menu/context/SysONExplorerTreeItemContextMenuEntryProvider.java
  doc/content/modules/user-manual/assets/images/release-notes-library-update-action.png
  doc/content/modules/user-manual/assets/images/release-notes-library-update-dialog.png
  doc/content/modules/user-manual/assets/images/release-notes-library-update-success.png
  doc/content/modules/user-manual/pages/features/library-import.adoc
  doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
  frontend/syson/src/index.tsx
Labels: pr: to review later, priority: high

#1137 [1029] Fix name resolution on element reference by implicit elements
  CHANGELOG.adoc
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controller/editingContext/checkers/SemanticCheckerService.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/export/ImportExportTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/export/checker/SysmlImportExportChecker.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/sysml/impl/ActionDefinitionImplTest.java
  backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/SpecializationImpl.java
  backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/TypeImpl.java
  backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/util/VirtualLinkAdapter.java
  doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
Labels: pr: to review soon, priority: high

#1142 [releng] Bump version to 2025.2.7
  backend/application/pom.xml
  backend/application/syson-application-configuration/pom.xml
  backend/application/syson-application/pom.xml
  backend/application/syson-frontend/pom.xml
  backend/application/syson-sysml-export/pom.xml
  backend/application/syson-sysml-import/pom.xml
  backend/application/syson-sysml-validation/pom.xml
  backend/metamodel/pom.xml
  backend/metamodel/syson-siriusweb-customnodes-metamodel-edit/pom.xml
  backend/metamodel/syson-siriusweb-customnodes-metamodel/pom.xml
  backend/metamodel/syson-sysml-metamodel-edit/pom.xml
  backend/metamodel/syson-sysml-metamodel/pom.xml
  backend/releng/pom.xml
  backend/releng/syson-test-coverage/pom.xml
  backend/services/pom.xml
  backend/services/syson-direct-edit-grammar/pom.xml
  backend/services/syson-services/pom.xml
  backend/services/syson-sysml-rest-api-services/pom.xml
  backend/tests/pom.xml
  backend/tests/syson-tests/pom.xml
  backend/views/pom.xml
  backend/views/syson-diagram-actionflow-view/pom.xml
  backend/views/syson-diagram-common-view/pom.xml
  backend/views/syson-diagram-general-view/pom.xml
  backend/views/syson-diagram-interconnection-view/pom.xml
  backend/views/syson-diagram-statetransition-view/pom.xml
  backend/views/syson-diagram-tests/pom.xml
  backend/views/syson-tree-explorer-view/pom.xml
  doc/content/antora.yml
  docker-compose.yml
  frontend/syson-components/package.json
  frontend/syson/package.json
  integration-tests/cypress/e2e/project/diagrams/diagramCreationTests.cy.ts
  integration-tests/package-lock.json
  integration-tests/package.json
  package-lock.json
  package.json
  pom.xml
Labels: pr: to review soon, priority: high
