Repository eclipse-syson/syson, pull requests merged in 2025-04, with the labels that each got.

#1145 [1143] Implement export of Decision Transition Usages
  CHANGELOG.adoc
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/export/ImportExportTests.java
  backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/textual/SysMLElementSerializer.java
  doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
Labels: pr: to review soon, priority: high

#1151 [1148] Fix computation of Succession source and target implicit features
  CHANGELOG.adoc
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/imports/ImportSysMLModelTest.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/imports/SysMLv2SemanticImportChecker.java
  backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/helper/ImplicitSpecializationSwitch.java
  doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
Labels: pr: to review soon, priority: high

#1159 [1158] Fix imported TransitionFeatureKind value on accept and do
  CHANGELOG.adoc
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/imports/ImportSysMLModelTest.java
  backend/application/syson-sysml-import/src/main/java/org/eclipse/syson/sysml/parser/translation/EAttributeTranslator.java
  doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
Labels: pr: to review soon, priority: high

#1156 [1155] Remove the imported EAnnotation from published libraries
  CHANGELOG.adoc
  backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/publication/SySONLibraryPublicationHandler.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/data/SysMLv2Identifiers.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/publication/SySONLibraryPublicationTests.java
  backend/application/syson-application/src/test/resources/scripts/SysMLv2-ImportedProject/dump-test-data.sh
  backend/application/syson-application/src/test/resources/scripts/SysMLv2-ImportedProject/initialize-test-data.sh
  backend/application/syson-application/src/test/resources/scripts/SysMLv2-ImportedProject/syson-test-database.sql
  doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
Labels: pr: to review soon, priority: high

#1165 [1164] Fix imported RequirementConstraintKind on assume and require
  CHANGELOG.adoc
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/imports/ImportSysMLModelTest.java
  backend/application/syson-sysml-import/src/main/java/org/eclipse/syson/sysml/parser/translation/EAttributeTranslator.java
  doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
Labels: pr: to review soon, priority: high

#1146 [test] Enable skipped tests
  doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
  integration-tests/cypress/e2e/project/details/details.cy.ts
  integration-tests/cypress/e2e/project/diagrams/diagramCreationTests.cy.ts
  integration-tests/cypress/e2e/project/diagrams/general-view/nodeCreationTests.cy.ts
  integration-tests/cypress/e2e/project/explorer/insertTextualSysMLv2Tests.cy.ts
  integration-tests/cypress/pages/Project.ts
  integration-tests/cypress/support/server/deleteProjectCommand.ts
  integration-tests/cypress/support/serverCommands.js
  integration-tests/cypress/support/testIdCommands.ts
  integration-tests/cypress/workbench/Explorer.ts
Labels: pr: to review soon, priority: high

#1161 [1160] Use TextArea for body properties
  CHANGELOG.adoc
  backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/configuration/SysMLv2PropertiesConfigurer.java
  backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/services/CoreFeaturesSwitch.java
  backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/services/DetailsViewService.java
  doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
Labels: pr: to review soon, priority: high

#1167 [cleanup] Refactor tests
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/libraries/SysONLibraryImportTestServer.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/migration/AnnotationMigrationParticipantTest.java
  backend/application/syson-application/src/test/resources/migrationParticipants/annotation/dump-test-data.sh
  backend/application/syson-application/src/test/resources/scripts/libraries/imports/dump-test-data.sh
  backend/application/syson-application/src/test/resources/scripts/libraries/imports/initialize-test-data.sh
  backend/application/syson-application/src/test/resources/scripts/libraries/imports/syson-test-database.sql
  backend/application/syson-application/src/test/resources/scripts/migrationParticipants/annotation/dump-test-data.sh
  backend/application/syson-application/src/test/resources/scripts/migrationParticipants/annotation/initialize-test-data.sh
  backend/application/syson-application/src/test/resources/scripts/migrationParticipants/annotation/syson-test-database.sql
Labels: pr: to review soon, priority: high

#1168 [test] Add possibility to launch tests without default libraries
  backend/application/syson-application/src/test/java/org/eclipse/syson/OnNoDefaultLibrariesTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/SysONNoDefaultLibrariesTestConfiguration.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/SysONNoLoadDefaultLibrariesOnApplicationStartTestConfiguration.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/SysONTestsProperties.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controller/objects/ObjectCreationTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controller/relatedelements/view/RelatedElementsViewTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVAddNewFeatureTypingFromPartUsageTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVAddNewSubsettingFromPartUsageTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVAnnotatingElementTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVBorderNodePortCreationTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVDropFromExplorerTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVEdgeCreationTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVRelationshipTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeActionFlowCreationTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeAnalysisCreationTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeExtensionCreationTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeInterconnectionCreationTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeRequirementCreationTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeStateTransitionCreationTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeStructureCreationTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeTemporalCreationTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/interconnection/view/IVAddNewBindingConnectorAsUsageFromPartUsageTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/interconnection/view/IVAddNewFlowConnectionFromPartUsageTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/interconnection/view/IVAddNewInterfaceFromPartUsageTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/interconnection/view/IVFlowConnectionFromPartUsageTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/rest/RestControllerIntegrationTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/tree/explorer/view/handlers/DropTreeItemHandlerTest.java
  scripts/check-coverage.jsh
Labels: pr: to review soon, priority: high

#1170 [1169] Update navigation bar menu icon
  CHANGELOG.adoc
  doc/content/modules/user-manual/assets/images/release-notes-navigation-bar-menu-icon.png
  doc/content/modules/user-manual/assets/images/release-notes-navigation-bar-menu.png
  doc/content/modules/user-manual/assets/images/release-notes-publication-libraries-menu.png
  doc/content/modules/user-manual/pages/features/library-import.adoc
  doc/content/modules/user-manual/pages/features/publication.adoc
  doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
  frontend/syson-components/src/extensions/navigationBarMenu/SysONNavigationBarMenuIcon.tsx
  frontend/syson-components/src/index.ts
  frontend/syson/src/index.tsx
Labels: pr: to review soon, priority: high

#1171 [doc] Update doc
  doc/content/modules/user-manual/pages/features/library-import.adoc
  doc/content/modules/user-manual/pages/features/publication.adoc
  doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
  scripts/check-coverage.jsh
Labels: pr: to review soon, priority: high

#1174 [1172] Uniformize the import of LiteralString value
  CHANGELOG.adoc
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/imports/ImportSysMLModelTest.java
  backend/application/syson-sysml-import/src/main/java/org/eclipse/syson/sysml/parser/translation/EAttributeTranslator.java
  doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
Labels: pr: to review soon, priority: high

#1175 [1173] Fix the export of LiteralString not wrapped in double quotes
  CHANGELOG.adoc
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/export/ImportExportTests.java
  backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/textual/SysMLElementSerializer.java
  backend/metamodel/syson-sysml-metamodel/src/test/java/org/eclipse/syson/sysml/textual/SysMLElementSerializerTest.java
  doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
Labels: pr: to review soon, priority: high

#1179 [1177] Add new SysMLv2 Library template
  CHANGELOG.adoc
  backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/sysmlv2/SysMLv2EditingContextActionHandler.java
  backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/sysmlv2/SysMLv2EditingContextActionProvider.java
  backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/sysmlv2/SysMLv2ProjectTemplatesInitializer.java
  backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/sysmlv2/SysMLv2ProjectTemplatesProvider.java
  backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/sysmlv2/SysMLv2StereotypeHandler.java
  backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/sysmlv2/SysMLv2StereotypeProvider.java
  backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/sysmlv2/SysONDefaultResourceProvider.java
  backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/sysmlv2/api/IDefaultSysMLv2ResourceProvider.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/templates/TemplatesControllerIntegrationTests.java
  doc/content/modules/user-manual/assets/images/hands-on-new-project.png
  doc/content/modules/user-manual/assets/images/hands-on-new-template.png
  doc/content/modules/user-manual/assets/images/homepage-new-project.png
  doc/content/modules/user-manual/assets/images/homepage-toolbar.png
  doc/content/modules/user-manual/pages/features/editor.adoc
  doc/content/modules/user-manual/pages/features/homepage.adoc
  doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
  doc/content/modules/user-manual/partials/libraries-action.adoc
  doc/content/modules/user-manual/partials/projects-action.adoc
Labels: pr: to review soon, priority: high

#1178 [1176] Fix creation of TransitionUsage to "Done" ActionUsage
  CHANGELOG.adoc
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVActionFlowTests.java
  backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewEdgeToolService.java
  backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewToolService.java
  backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/services/InterconnectionViewToolService.java
  doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
  scripts/check-coverage.jsh
Labels: pr: to review soon, priority: high

#1163 [1162] Implement TextualRepresentation textual export
  CHANGELOG.adoc
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/export/ImportExportTests.java
  backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/textual/SysMLElementSerializer.java
  doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
Labels: pr: to review soon, priority: high

#1184 [1183] Fix Element#isLibraryElement for elements inside LibraryPackage
  CHANGELOG.adoc
  backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/ElementImpl.java
  backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/util/ElementUtil.java
  backend/metamodel/syson-sysml-metamodel/src/test/java/org/eclipse/syson/sysml/impl/ElementTest.java
  doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
Labels: pr: to review soon, priority: low

#1187 [releng] Switch to Sirius Web 2025.2.8
  CHANGELOG.adoc
  backend/application/syson-application-configuration/pom.xml
  backend/application/syson-application/pom.xml
  backend/application/syson-sysml-export/pom.xml
  backend/application/syson-sysml-import/pom.xml
  backend/application/syson-sysml-validation/pom.xml
  backend/metamodel/syson-siriusweb-customnodes-metamodel-edit/pom.xml
  backend/metamodel/syson-siriusweb-customnodes-metamodel/pom.xml
  backend/services/syson-direct-edit-grammar/pom.xml
  backend/services/syson-services/pom.xml
  backend/services/syson-sysml-rest-api-services/pom.xml
  backend/views/syson-diagram-actionflow-view/pom.xml
  backend/views/syson-diagram-common-view/pom.xml
  backend/views/syson-diagram-general-view/pom.xml
  backend/views/syson-diagram-interconnection-view/pom.xml
  backend/views/syson-diagram-statetransition-view/pom.xml
  backend/views/syson-diagram-tests/pom.xml
  backend/views/syson-tree-explorer-view/pom.xml
  doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
  frontend/syson-components/package.json
  frontend/syson-components/src/nodes/imported_package/SysMLImportedPackageNodeConverter.ts
  frontend/syson-components/src/nodes/note/SysMLNoteNodeConverter.ts
  frontend/syson-components/src/nodes/package/SysMLPackageNodeConverter.ts
  frontend/syson/package.json
  package-lock.json
Labels: pr: to review soon, priority: high

#1188 [releng] Bump version to 2025.2.8
  backend/application/pom.xml
  backend/application/syson-application-configuration/pom.xml
  backend/application/syson-application/pom.xml
  backend/application/syson-frontend/pom.xml
  backend/application/syson-sysml-export/pom.xml
  backend/application/syson-sysml-import/pom.xml
  backend/application/syson-sysml-validation/pom.xml
  backend/metamodel/pom.xml
  backend/metamodel/syson-siriusweb-customnodes-metamodel-edit/pom.xml
  backend/metamodel/syson-siriusweb-customnodes-metamodel/pom.xml
  backend/metamodel/syson-sysml-metamodel-edit/pom.xml
  backend/metamodel/syson-sysml-metamodel/pom.xml
  backend/releng/pom.xml
  backend/releng/syson-test-coverage/pom.xml
  backend/services/pom.xml
  backend/services/syson-direct-edit-grammar/pom.xml
  backend/services/syson-services/pom.xml
  backend/services/syson-sysml-rest-api-services/pom.xml
  backend/tests/pom.xml
  backend/tests/syson-tests/pom.xml
  backend/views/pom.xml
  backend/views/syson-diagram-actionflow-view/pom.xml
  backend/views/syson-diagram-common-view/pom.xml
  backend/views/syson-diagram-general-view/pom.xml
  backend/views/syson-diagram-interconnection-view/pom.xml
  backend/views/syson-diagram-statetransition-view/pom.xml
  backend/views/syson-diagram-tests/pom.xml
  backend/views/syson-tree-explorer-view/pom.xml
  doc/content/antora.yml
  docker-compose.yml
  frontend/syson-components/package.json
  frontend/syson/package.json
  integration-tests/package-lock.json
  integration-tests/package.json
  package-lock.json
  package.json
  pom.xml
Labels: pr: to review soon, priority: high

#1189 [releng] Switch to Sirius Web 2025.2.9
  CHANGELOG.adoc
  backend/application/syson-application-configuration/pom.xml
  backend/application/syson-application/pom.xml
  backend/application/syson-sysml-export/pom.xml
  backend/application/syson-sysml-import/pom.xml
  backend/application/syson-sysml-validation/pom.xml
  backend/metamodel/syson-siriusweb-customnodes-metamodel-edit/pom.xml
  backend/metamodel/syson-siriusweb-customnodes-metamodel/pom.xml
  backend/services/syson-direct-edit-grammar/pom.xml
  backend/services/syson-services/pom.xml
  backend/services/syson-sysml-rest-api-services/pom.xml
  backend/views/syson-diagram-actionflow-view/pom.xml
  backend/views/syson-diagram-common-view/pom.xml
  backend/views/syson-diagram-general-view/pom.xml
  backend/views/syson-diagram-interconnection-view/pom.xml
  backend/views/syson-diagram-statetransition-view/pom.xml
  backend/views/syson-diagram-tests/pom.xml
  backend/views/syson-tree-explorer-view/pom.xml
  doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
  frontend/syson-components/package.json
  frontend/syson-components/src/nodes/imported_package/SysMLImportedPackageNodeConverter.ts
  frontend/syson-components/src/nodes/note/SysMLNoteNodeConverter.ts
  frontend/syson-components/src/nodes/package/SysMLPackageNodeConverter.ts
  frontend/syson/package.json
  package-lock.json
Labels: pr: to review soon, priority: high

#1190 [releng] Bump version to 2025.2.9
  backend/application/pom.xml
  backend/application/syson-application-configuration/pom.xml
  backend/application/syson-application/pom.xml
  backend/application/syson-frontend/pom.xml
  backend/application/syson-sysml-export/pom.xml
  backend/application/syson-sysml-import/pom.xml
  backend/application/syson-sysml-validation/pom.xml
  backend/metamodel/pom.xml
  backend/metamodel/syson-siriusweb-customnodes-metamodel-edit/pom.xml
  backend/metamodel/syson-siriusweb-customnodes-metamodel/pom.xml
  backend/metamodel/syson-sysml-metamodel-edit/pom.xml
  backend/metamodel/syson-sysml-metamodel/pom.xml
  backend/releng/pom.xml
  backend/releng/syson-test-coverage/pom.xml
  backend/services/pom.xml
  backend/services/syson-direct-edit-grammar/pom.xml
  backend/services/syson-services/pom.xml
  backend/services/syson-sysml-rest-api-services/pom.xml
  backend/tests/pom.xml
  backend/tests/syson-tests/pom.xml
  backend/views/pom.xml
  backend/views/syson-diagram-actionflow-view/pom.xml
  backend/views/syson-diagram-common-view/pom.xml
  backend/views/syson-diagram-general-view/pom.xml
  backend/views/syson-diagram-interconnection-view/pom.xml
  backend/views/syson-diagram-statetransition-view/pom.xml
  backend/views/syson-diagram-tests/pom.xml
  backend/views/syson-tree-explorer-view/pom.xml
  doc/content/antora.yml
  docker-compose.yml
  frontend/syson-components/package.json
  frontend/syson/package.json
  integration-tests/package-lock.json
  integration-tests/package.json
  package-lock.json
  package.json
  pom.xml
Labels: pr: to review soon, priority: high

#1201 [releng] Bump version to 2025.2.10
  CHANGELOG.adoc
  backend/application/pom.xml
  backend/application/syson-application-configuration/pom.xml
  backend/application/syson-application/pom.xml
  backend/application/syson-frontend/pom.xml
  backend/application/syson-sysml-export/pom.xml
  backend/application/syson-sysml-import/pom.xml
  backend/application/syson-sysml-validation/pom.xml
  backend/metamodel/pom.xml
  backend/metamodel/syson-siriusweb-customnodes-metamodel-edit/pom.xml
  backend/metamodel/syson-siriusweb-customnodes-metamodel/pom.xml
  backend/metamodel/syson-sysml-metamodel-edit/pom.xml
  backend/metamodel/syson-sysml-metamodel/pom.xml
  backend/releng/pom.xml
  backend/releng/syson-test-coverage/pom.xml
  backend/services/pom.xml
  backend/services/syson-direct-edit-grammar/pom.xml
  backend/services/syson-services/pom.xml
  backend/services/syson-sysml-rest-api-services/pom.xml
  backend/tests/pom.xml
  backend/tests/syson-tests/pom.xml
  backend/views/pom.xml
  backend/views/syson-diagram-actionflow-view/pom.xml
  backend/views/syson-diagram-common-view/pom.xml
  backend/views/syson-diagram-general-view/pom.xml
  backend/views/syson-diagram-interconnection-view/pom.xml
  backend/views/syson-diagram-statetransition-view/pom.xml
  backend/views/syson-diagram-tests/pom.xml
  backend/views/syson-tree-explorer-view/pom.xml
  doc/content/antora.yml
  doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
  docker-compose.yml
  frontend/syson-components/package.json
  frontend/syson/package.json
  integration-tests/package-lock.json
  integration-tests/package.json
  package-lock.json
  package.json
  pom.xml
Labels: pr: to review soon, priority: high

#1206 [1200] Add Comment tool on Dependency graphical edge
  CHANGELOG.adoc
  backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/AnnotatingElementImpl.java
  backend/services/syson-services/src/main/java/org/eclipse/syson/services/RelatedElementsSwitch.java
  backend/services/syson-services/src/main/java/org/eclipse/syson/services/ToolService.java
  backend/views/syson-diagram-actionflow-view/src/main/java/org/eclipse/syson/diagram/actionflow/view/ActionFlowViewDiagramDescriptionProvider.java
  backend/views/syson-diagram-actionflow-view/src/main/java/org/eclipse/syson/diagram/actionflow/view/edges/DependencyEdgeDescriptionProvider.java
  backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/edges/AbstractAllocateEdgeDescriptionProvider.java
  backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/edges/AbstractDefinitionOwnedUsageEdgeDescriptionProvider.java
  backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/edges/AbstractDependencyEdgeDescriptionProvider.java
  backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/edges/AbstractEdgeDescriptionProvider.java
  backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/edges/AbstractFeatureTypingEdgeDescriptionProvider.java
  backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/edges/AbstractRedefinitionEdgeDescriptionProvider.java
  backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/edges/AbstractSubclassificationEdgeDescriptionProvider.java
  backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/edges/AbstractSubsettingEdgeDescriptionProvider.java
  backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/edges/AbstractSuccessionEdgeDescriptionProvider.java
  backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/edges/AbstractUsageNestedUsageEdgeDescriptionProvider.java
  backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/edges/AnnotationEdgeDescriptionProvider.java
  backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/edges/TransitionEdgeDescriptionProvider.java
  backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/AbstractViewNodeToolsWithoutSectionSwitch.java
  backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewNodeService.java
  backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/description/ToolDescriptionService.java
  backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/tools/AnnotatingElementOnRelationshipNodeToolProvider.java
  backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/GeneralViewDiagramDescriptionProvider.java
  backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/edges/DependencyEdgeDescriptionProvider.java
  backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/edges/NestedActorEdgeDescriptionProvider.java
  backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/services/GeneralViewNodeToolsWithoutSectionSwitch.java
  doc/content/modules/user-manual/assets/images/release-notes-gv-comment-on-dependency.png
  doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
Labels: pr: to review soon, priority: high

#1207 [releng] Switch to Sirius Web 2025.2.11
  CHANGELOG.adoc
  backend/application/syson-application-configuration/pom.xml
  backend/application/syson-application/pom.xml
  backend/application/syson-sysml-export/pom.xml
  backend/application/syson-sysml-import/pom.xml
  backend/application/syson-sysml-validation/pom.xml
  backend/metamodel/syson-siriusweb-customnodes-metamodel-edit/pom.xml
  backend/metamodel/syson-siriusweb-customnodes-metamodel/pom.xml
  backend/services/syson-direct-edit-grammar/pom.xml
  backend/services/syson-services/pom.xml
  backend/services/syson-sysml-rest-api-services/pom.xml
  backend/views/syson-diagram-actionflow-view/pom.xml
  backend/views/syson-diagram-common-view/pom.xml
  backend/views/syson-diagram-general-view/pom.xml
  backend/views/syson-diagram-interconnection-view/pom.xml
  backend/views/syson-diagram-statetransition-view/pom.xml
  backend/views/syson-diagram-tests/pom.xml
  backend/views/syson-tree-explorer-view/pom.xml
  doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
  frontend/syson-components/package.json
  frontend/syson/package.json
  package-lock.json
Labels: pr: to review soon, priority: high

#1209 [releng] Bump version to 2025.2.11
  backend/application/pom.xml
  backend/application/syson-application-configuration/pom.xml
  backend/application/syson-application/pom.xml
  backend/application/syson-frontend/pom.xml
  backend/application/syson-sysml-export/pom.xml
  backend/application/syson-sysml-import/pom.xml
  backend/application/syson-sysml-validation/pom.xml
  backend/metamodel/pom.xml
  backend/metamodel/syson-siriusweb-customnodes-metamodel-edit/pom.xml
  backend/metamodel/syson-siriusweb-customnodes-metamodel/pom.xml
  backend/metamodel/syson-sysml-metamodel-edit/pom.xml
  backend/metamodel/syson-sysml-metamodel/pom.xml
  backend/releng/pom.xml
  backend/releng/syson-test-coverage/pom.xml
  backend/services/pom.xml
  backend/services/syson-direct-edit-grammar/pom.xml
  backend/services/syson-services/pom.xml
  backend/services/syson-sysml-rest-api-services/pom.xml
  backend/tests/pom.xml
  backend/tests/syson-tests/pom.xml
  backend/views/pom.xml
  backend/views/syson-diagram-actionflow-view/pom.xml
  backend/views/syson-diagram-common-view/pom.xml
  backend/views/syson-diagram-general-view/pom.xml
  backend/views/syson-diagram-interconnection-view/pom.xml
  backend/views/syson-diagram-statetransition-view/pom.xml
  backend/views/syson-diagram-tests/pom.xml
  backend/views/syson-tree-explorer-view/pom.xml
  doc/content/antora.yml
  docker-compose.yml
  frontend/syson-components/package.json
  frontend/syson/package.json
  integration-tests/package-lock.json
  integration-tests/package.json
  package-lock.json
  package.json
  pom.xml
Labels: pr: to review soon, priority: high

#1227 [releng] Update sbom workflows
  .github/workflows/generate-maven-sbom.yml
  .github/workflows/generate-npm-sbom.yml
Labels: pr: to review soon, priority: high

#1228 [releng] Update sbom workflows
  .github/workflows/generate-maven-sbom.yml
  .github/workflows/generate-npm-sbom.yml
Labels: pr: to review soon, priority: high

#1229 [releng] Update sbom workflows
  .github/workflows/generate-maven-sbom.yml
  .github/workflows/generate-npm-sbom.yml
Labels: pr: to review soon, priority: high

#1230 [releng] Update sbom workflows
  .github/workflows/generate-maven-sbom.yml
  .github/workflows/generate-npm-sbom.yml
Labels: pr: to review soon, priority: high

#1231 [releng] Update sbom workflows
  .github/workflows/generate-maven-sbom.yml
  .github/workflows/generate-npm-sbom.yml
Labels: pr: to review soon, priority: high

#1232 [releng] Update sbom workflows
  .github/workflows/generate-maven-sbom.yml
  .github/workflows/generate-npm-sbom.yml
Labels: pr: to review soon, priority: high

#1243 [releng] Prepare next release
  CHANGELOG.adoc
  doc/content/modules/user-manual/pages/release-notes/2025.6.0.adoc
  doc/content/modules/user-manual/pages/release-notes/release-notes.adoc
  doc/docs-site/antora-playbook.yml
Labels: pr: to review soon, priority: high

#1193 [1192] Add ConnectionDefinition in General View diagram
  CHANGELOG.adoc
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVTopNodeCreationTests.java
  backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/GeneralViewDiagramDescriptionProvider.java
  backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/GeneralViewNodeDescriptionProviderSwitch.java
  doc/content/modules/user-manual/assets/images/connection-definition-nodes.png
  doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
  doc/content/modules/user-manual/pages/release-notes/2025.6.0.adoc
Labels: pr: to review later, priority: low

#1215 Implement textual export of ForkNode, JoinNode and MergeNode
  CHANGELOG.adoc
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/export/ImportExportTests.java
  backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/textual/SysMLElementSerializer.java
  doc/content/modules/user-manual/pages/release-notes/2025.6.0.adoc
Labels: pr: to review later, priority: low

#1250 [1249] Implement textual import/export of AcceptActionUsage
  CHANGELOG.adoc
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/export/ImportExportTests.java
  backend/application/syson-sysml-import/src/main/java/org/eclipse/syson/sysml/ASTTransformer.java
  backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/textual/SysMLElementSerializer.java
  doc/content/modules/user-manual/pages/release-notes/2025.6.0.adoc
Labels: pr: to review soon, priority: high

#1248 [1247] Type new ViewUsage from Explorer view with GeneralView ViewDef
  CHANGELOG.adoc
  backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/services/GetChildCreationSwitch.java
  backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/services/GetIntermediateContainerCreationSwitch.java
  backend/application/syson-application-configuration/src/test/java/org/eclipse/syson/application/services/GetChildCreationSwitchTest.java
  backend/services/syson-services/src/main/java/org/eclipse/syson/services/ElementInitializerSwitch.java
  backend/services/syson-services/src/test/java/org/eclipse/syson/services/ElementInitializerSwitchTest.java
  doc/content/modules/user-manual/pages/release-notes/2025.6.0.adoc
Labels: pr: to review soon, priority: high

#1253 [1252] Implement textual export of TriggerInvocationExpression
  CHANGELOG.adoc
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/export/ImportExportTests.java
  backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/textual/SysMLElementSerializer.java
  doc/content/modules/user-manual/pages/release-notes/2025.6.0.adoc
Labels: pr: to review soon, priority: high

#1236 [1233] Add new tools to create State sub actions in general view
  CHANGELOG.adoc
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeStateTransitionCreationTests.java
  backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewCreateService.java
  backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewToolService.java
  backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/tools/StateSubactionNodeToolProvider.java
  backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/nodes/ActionsCompartmentNodeDescriptionProvider.java
  backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/services/GeneralViewNodeToolSectionSwitch.java
  doc/content/modules/user-manual/pages/release-notes/2025.6.0.adoc
Labels: pr: to review soon, priority: high

#1256 [1255] Improve label of TransitionUsage to handle "AcceptParameterPart"
  CHANGELOG.adoc
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVStateTransitionUsageTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/data/GeneralViewStateTransitionUsageProjectData.java
  backend/application/syson-application/src/test/resources/scripts/database-content/GeneralView-StateTransitionUsages.sql
  backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/textual/SysMLElementSerializer.java
  backend/views/syson-diagram-actionflow-view/src/test/java/org/eclipse/syson/diagram/actionflow/view/ActionFlowViewDiagramDescriptionTests.java
  backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/edges/AbstractTransitionEdgeDescriptionProvider.java
  backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewLabelService.java
  backend/views/syson-diagram-general-view/src/test/java/org/eclipse/syson/diagram/general/view/GeneralViewDiagramDescriptionTests.java
  backend/views/syson-diagram-statetransition-view/src/test/java/org/eclipse/syson/diagram/statetransition/view/StateTransitionViewDiagramDescriptionTests.java
  doc/content/modules/user-manual/assets/images/StateTransitionUsageLabels.png
  doc/content/modules/user-manual/pages/release-notes/2025.6.0.adoc
Labels: pr: to review soon, priority: high

#1234 [doc] Add shapes about ViewUsages and ViewDefinitions
  CHANGELOG.adoc
  doc/shapes/2025.06/add_support_for_viewusages.adoc
  doc/shapes/2025.06/diagrams_on_view_usages.adoc
  doc/shapes/2025.06/display_view_usages_in_diagrams.adoc
  doc/shapes/2025.06/images/diagram_element_manage_visibility_view_frame.png
  doc/shapes/2025.06/images/diagram_element_showhide_view_frame.png
  doc/shapes/2025.06/images/diagram_element_view_as_menu.png
  doc/shapes/2025.06/images/explorer_view_usage.png
  doc/shapes/2025.06/images/new_object_menu_view_usage.png
  doc/shapes/2025.06/images/new_representation_menu.png
  doc/shapes/2025.06/manage_update_of_view_usages_in_diagrams.adoc
Labels: package: syson-application, type: documentation

#1262 [1258] Add required libraries as dependencies when publishing a project
  CHANGELOG.adoc
  backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/publication/SysONLibraryDependencyCollector.java
  backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/publication/SysONLibraryPublicationHandler.java
  backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/publication/api/ISysONLibraryDependencyCollector.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/data/ProjectWithUnusedBatmobileLibraryDependencyTestProjectData.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/data/ProjectWithUsedBatmobileLibraryDependencyTestProjectData.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/libraries/publication/SySONLibraryPublicationTests.java
  backend/application/syson-application/src/test/resources/scripts/database-content/SysMLv2-ProjectWithUnusedBatmobileLibraryDependency.sql
  backend/application/syson-application/src/test/resources/scripts/database-content/SysMLv2-ProjectWithUsedBatmobileLibraryDependency.sql
  doc/content/modules/user-manual/pages/release-notes/2025.6.0.adoc
Labels: pr: to review soon, priority: high

#1265 [test] Add an integration test for the Details view
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/details/view/DetailsViewControllerIntegrationTests.java
Labels: pr: to review later, priority: low
