Repository eclipse-syson/syson, pull requests merged in 2025-02, with the labels that each got.

#989 [987] Implementation of DnD in SysOn Explorer view
  CHANGELOG.adoc
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/projects/ProjectDataVersioningRestControllerIntegrationTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/data/SysMLv2Identifiers.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/services/SysMLReadOnlyServiceTest.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/tree/explorer/view/handlers/DropTreeItemHandlerTest.java
  backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/helper/EMFUtils.java
  backend/services/syson-services/src/main/java/org/eclipse/syson/services/SysMLMoveElementService.java
  backend/services/syson-services/src/main/java/org/eclipse/syson/services/SysMLReadOnlyService.java
  backend/services/syson-services/src/main/java/org/eclipse/syson/services/ToolService.java
  backend/services/syson-services/src/main/java/org/eclipse/syson/services/UtilService.java
  backend/services/syson-services/src/main/java/org/eclipse/syson/services/api/ISysMLMoveElementService.java
  backend/services/syson-services/src/main/java/org/eclipse/syson/services/api/ISysMLReadOnlyService.java
  backend/services/syson-services/src/main/java/org/eclipse/syson/services/api/MoveStatus.java
  backend/services/syson-services/src/test/java/org/eclipse/syson/services/SysMLMoveElementServiceTest.java
  backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewToolService.java
  backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/services/InterconnectionViewToolService.java
  backend/views/syson-tree-explorer-view/src/main/java/org/eclipse/syson/tree/explorer/view/handlers/DropTreeItemHandler.java
  doc/content/modules/user-manual/pages/features/explorer.adoc
  doc/content/modules/user-manual/pages/release-notes/2025.2.0.adoc
Labels: pr: to review soon, priority: high

#990 [cleanup] Move kermllibrary and sysmllibrary constants to ElementUtils
  backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/configuration/SysMLStandardLibrariesConfiguration.java
  backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/configuration/SysMLv2RewriteProxiesResourcesFilter.java
  backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/services/DetailsViewService.java
  backend/application/syson-application-configuration/src/test/java/org/eclipse/syson/application/configuration/SysMLEditingContextProcessorTest.java
  backend/application/syson-sysml-export/src/main/java/org/eclipse/syson/sysml/export/SysMLv2EditingContextPersistenceFilter.java
  backend/metamodel/syson-sysml-metamodel-edit/src/main/java/org/eclipse/syson/sysml/provider/ElementItemProvider.java
  backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/util/ElementUtil.java
  backend/metamodel/syson-sysml-metamodel/src/test/java/org/eclipse/syson/sysml/metamodel/ElementUtilTest.java
  backend/services/syson-services/src/main/java/org/eclipse/syson/services/SysMLReadOnlyService.java
  backend/services/syson-sysml-rest-api-services/src/main/java/org/eclipse/syson/sysml/rest/api/SysONObjectRestService.java
  backend/views/syson-tree-explorer-view/src/main/java/org/eclipse/syson/tree/explorer/view/services/SysONExplorerFilterService.java
  backend/views/syson-tree-explorer-view/src/test/java/org/eclipse/syson/tree/explorer/view/services/SysONExplorerFilterServiceTest.java
Labels: pr: to review soon, priority: high

#993 [992] Export Concern and Stakeholder concepts
  CHANGELOG.adoc
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/export/ImportExportTests.java
  backend/application/syson-sysml-export/src/main/java/org/eclipse/syson/sysml/export/SysMLElementSerializer.java
  backend/application/syson-sysml-export/src/main/java/org/eclipse/syson/sysml/export/utils/SysMLKeywordSwitch.java
  doc/content/modules/user-manual/pages/release-notes/2025.2.0.adoc
Labels: pr: to review soon, priority: high

#999 [998] Fix label of PortUsage
  CHANGELOG.adoc
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/export/ImportExportTests.java
  backend/services/syson-services/src/main/java/org/eclipse/syson/services/MultiLineLabelSwitch.java
  doc/content/modules/user-manual/pages/release-notes/2025.2.0.adoc
Labels: pr: to review soon, priority: high

#1010 [releng] Fix Sirius Web version in syson-sysml-validation
  backend/application/syson-sysml-validation/pom.xml
  integration-tests/cypress/e2e/project/explorer/insertTextualSysMLv2Tests.cy.ts
  integration-tests/cypress/workbench/Explorer.ts
  scripts/update-sirius-web.js
Labels: pr: to review soon, priority: high

#1013 [1012] Allow package nodes to be smaller than their default size
  CHANGELOG.adoc
  doc/content/modules/user-manual/pages/release-notes/2025.2.0.adoc
  frontend/syson-components/src/nodes/package/SysMLPackageNodeLayoutHandler.ts
Labels: pr: to review soon, priority: low

#1008 [1006] Display isInitial and isDefault of FeatureValue Core tab
  CHANGELOG.adoc
  backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/services/CoreFeaturesSwitch.java
  backend/application/syson-application-configuration/src/test/java/org/eclipse/syson/application/services/DetailsViewServiceTest.java
  doc/content/modules/user-manual/pages/release-notes/2025.2.0.adoc
Labels: pr: to review soon, priority: high

#1016 [releng] Bump version to 2025.1.6
  backend/application/pom.xml
  backend/application/syson-application-configuration/pom.xml
  backend/application/syson-application/pom.xml
  backend/application/syson-application/src/main/resources/application-dev.properties
  backend/application/syson-frontend/pom.xml
  backend/application/syson-sysml-export/pom.xml
  backend/application/syson-sysml-import/pom.xml
  backend/application/syson-sysml-validation/pom.xml
  backend/metamodel/pom.xml
  backend/metamodel/syson-siriusweb-customnodes-metamodel-edit/pom.xml
  backend/metamodel/syson-siriusweb-customnodes-metamodel/pom.xml
  backend/metamodel/syson-sysml-metamodel-edit/pom.xml
  backend/metamodel/syson-sysml-metamodel/pom.xml
  backend/releng/pom.xml
  backend/releng/syson-test-coverage/pom.xml
  backend/services/pom.xml
  backend/services/syson-direct-edit-grammar/pom.xml
  backend/services/syson-services/pom.xml
  backend/services/syson-sysml-rest-api-services/pom.xml
  backend/tests/pom.xml
  backend/tests/syson-tests/pom.xml
  backend/views/pom.xml
  backend/views/syson-diagram-actionflow-view/pom.xml
  backend/views/syson-diagram-common-view/pom.xml
  backend/views/syson-diagram-general-view/pom.xml
  backend/views/syson-diagram-interconnection-view/pom.xml
  backend/views/syson-diagram-statetransition-view/pom.xml
  backend/views/syson-diagram-tests/pom.xml
  backend/views/syson-tree-explorer-view/pom.xml
  doc/content/antora.yml
  docker-compose.yml
  frontend/syson-components/package.json
  frontend/syson/package.json
  frontend/syson/src/extensions/SysONFooter.tsx
  integration-tests/package-lock.json
  integration-tests/package.json
  package-lock.json
  package.json
  pom.xml
Labels: pr: to review soon, priority: high

#1014 Add SBOM generation and upload to DependencyTrack workflows
  .github/workflows/generate-maven-sbom.yml
  .github/workflows/generate-npm-sbom.yml
Labels: pr: to review soon, priority: high

#1019 [1018] Rework library loading to be extensible and re-usable
  CHANGELOG.adoc
  backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/configuration/SysMLEditingContextProcessor.java
  backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/configuration/SysMLStandardLibrariesConfiguration.java
  backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/configuration/SysONDefaultLibrariesConfiguration.java
  backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/libraries/SysONLibraryLoader.java
  backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/libraries/SysONLibraryLoadingDefinition.java
  backend/application/syson-application-configuration/src/test/java/org/eclipse/syson/application/configuration/SysMLEditingContextProcessorTest.java
  backend/application/syson-sysml-import/src/test/java/org/eclipse/syson/sysml/ASTTransformerTest.java
  doc/content/modules/user-manual/pages/release-notes/2025.2.0.adoc
  scripts/check-coverage.jsh
Labels: pr: to review soon, priority: high

#1022 [1009] Allow SysMLFactory to create null unsettable Enum
  CHANGELOG.adoc
  backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/SysmlFactoryImpl.java
  doc/content/modules/user-manual/pages/release-notes/2025.2.0.adoc
Labels: pr: to review soon, priority: high

#1027 [1012] Allow import package nodes to be smaller than their default size
  CHANGELOG.adoc
  doc/content/modules/user-manual/pages/release-notes/2025.2.0.adoc
  frontend/syson-components/src/nodes/imported_package/SysMLImportedPackageNodeLayoutHandler.ts
  frontend/syson-components/src/nodes/package/SysMLPackageNodeLayoutHandler.ts
Labels: pr: to review soon, priority: high

#1044 [releng] Switch to Sirius Web 2025.1.7
  backend/application/syson-application-configuration/pom.xml
  backend/application/syson-application/pom.xml
  backend/application/syson-sysml-export/pom.xml
  backend/application/syson-sysml-import/pom.xml
  backend/application/syson-sysml-validation/pom.xml
  backend/metamodel/syson-siriusweb-customnodes-metamodel-edit/pom.xml
  backend/metamodel/syson-siriusweb-customnodes-metamodel/pom.xml
  backend/services/syson-direct-edit-grammar/pom.xml
  backend/services/syson-services/pom.xml
  backend/services/syson-sysml-rest-api-services/pom.xml
  backend/views/syson-diagram-actionflow-view/pom.xml
  backend/views/syson-diagram-common-view/pom.xml
  backend/views/syson-diagram-general-view/pom.xml
  backend/views/syson-diagram-interconnection-view/pom.xml
  backend/views/syson-diagram-statetransition-view/pom.xml
  backend/views/syson-diagram-tests/pom.xml
  backend/views/syson-tree-explorer-view/pom.xml
  frontend/syson-components/package.json
  frontend/syson/package.json
  package-lock.json
Labels: pr: to review soon, priority: high

#1054 [releng] Remove Libraries Menu
  frontend/syson/src/extensions/SysONExtensionRegistryMergeStrategy.ts
  frontend/syson/src/index.tsx
Labels: pr: to review soon, priority: high

#1057 [releng] Bump version to 2025.1.8
  backend/application/pom.xml
  backend/application/syson-application-configuration/pom.xml
  backend/application/syson-application/pom.xml
  backend/application/syson-frontend/pom.xml
  backend/application/syson-sysml-export/pom.xml
  backend/application/syson-sysml-import/pom.xml
  backend/application/syson-sysml-validation/pom.xml
  backend/metamodel/pom.xml
  backend/metamodel/syson-siriusweb-customnodes-metamodel-edit/pom.xml
  backend/metamodel/syson-siriusweb-customnodes-metamodel/pom.xml
  backend/metamodel/syson-sysml-metamodel-edit/pom.xml
  backend/metamodel/syson-sysml-metamodel/pom.xml
  backend/releng/pom.xml
  backend/releng/syson-test-coverage/pom.xml
  backend/services/pom.xml
  backend/services/syson-direct-edit-grammar/pom.xml
  backend/services/syson-services/pom.xml
  backend/services/syson-sysml-rest-api-services/pom.xml
  backend/tests/pom.xml
  backend/tests/syson-tests/pom.xml
  backend/views/pom.xml
  backend/views/syson-diagram-actionflow-view/pom.xml
  backend/views/syson-diagram-common-view/pom.xml
  backend/views/syson-diagram-general-view/pom.xml
  backend/views/syson-diagram-interconnection-view/pom.xml
  backend/views/syson-diagram-statetransition-view/pom.xml
  backend/views/syson-diagram-tests/pom.xml
  backend/views/syson-tree-explorer-view/pom.xml
  doc/content/antora.yml
  docker-compose.yml
  frontend/syson-components/package.json
  frontend/syson/package.json
  frontend/syson/src/extensions/SysONFooter.tsx
  integration-tests/package-lock.json
  integration-tests/package.json
  package-lock.json
  package.json
  pom.xml
Labels: pr: to review soon, priority: high

#1058 [releng] Switch to Sirius Web 2025.2.0
  CHANGELOG.adoc
  backend/application/syson-application-configuration/pom.xml
  backend/application/syson-application/pom.xml
  backend/application/syson-sysml-export/pom.xml
  backend/application/syson-sysml-import/pom.xml
  backend/application/syson-sysml-validation/pom.xml
  backend/metamodel/syson-siriusweb-customnodes-metamodel-edit/pom.xml
  backend/metamodel/syson-siriusweb-customnodes-metamodel/pom.xml
  backend/services/syson-direct-edit-grammar/pom.xml
  backend/services/syson-services/pom.xml
  backend/services/syson-sysml-rest-api-services/pom.xml
  backend/views/syson-diagram-actionflow-view/pom.xml
  backend/views/syson-diagram-common-view/pom.xml
  backend/views/syson-diagram-general-view/pom.xml
  backend/views/syson-diagram-interconnection-view/pom.xml
  backend/views/syson-diagram-statetransition-view/pom.xml
  backend/views/syson-diagram-tests/pom.xml
  backend/views/syson-tree-explorer-view/pom.xml
  doc/content/modules/user-manual/pages/release-notes/2025.2.0.adoc
  frontend/syson-components/package.json
  frontend/syson/package.json
  package-lock.json
Labels: pr: to review soon, priority: high

#1059 [releng] Add missing sirius-components-widget-table frontend dependency
  backend/application/syson-application/src/test/resources/scripts/cleanup.sql
  frontend/syson-components/package.json
  frontend/syson/package.json
  frontend/syson/src/extensions/SysONExtensionRegistryMergeStrategy.ts
  package-lock.json
  scripts/update-sirius-web.js
Labels: pr: to review soon, priority: high

#1065 [releng] Prepare next release
  CHANGELOG.adoc
  doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
  doc/content/modules/user-manual/pages/release-notes/release-notes.adoc
  doc/docs-site/antora-playbook.yml
  docker-compose.yml
Labels: pr: to review soon, priority: high

#1064 [1061] Add ellipsis on package label
  CHANGELOG.adoc
  backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/nodes/AbstractPackageNodeDescriptionProvider.java
  doc/content/modules/user-manual/assets/images/release-notes-package-name-ellipsis-overflow.png
  doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
Labels: pr: to review soon, priority: low

#945 [doc] Add a shape to support library publication
  CHANGELOG.adoc
  doc/shapes/2025.02/add_support_for_library_publication.adoc
  doc/shapes/2025.02/images/add_support_for_library_publication_01.png
  doc/shapes/2025.02/images/add_support_for_library_publication_02.png
  doc/shapes/2025.02/images/add_support_for_library_publication_03.png
Labels: pr: to review soon, priority: high

#1034 [1033] Remove filter condition on root namespace for diagram creation
  CHANGELOG.adoc
  backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewCreateService.java
  doc/content/modules/user-manual/assets/images/release-notes-create-diagram-on-root-namespace-element.png
  doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
  integration-tests/cypress/e2e/project/diagrams/diagramCreationTests.cy.ts
Labels: pr: to review soon, priority: low

#1036 [960] Display possible 'subject' Usages in a tree instead of a list
  CHANGELOG.adoc
  backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewToolService.java
  backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/tools/SubjectCompartmentNodeToolProvider.java
  doc/content/modules/user-manual/assets/images/release-notes-gv-subject-creation-selection-dialog-tree.png
  doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
Labels: pr: to review later, priority: low

#1060 [cleanup] Remove the use of IObjectService to prepare for changes in Sirius Web
  backend/application/syson-application-configuration/src/main/java/org/eclipse/syson/application/services/SysMLv2EditService.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controller/editingContext/checkers/CheckElementInParent.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controller/editingContext/checkers/SemanticCheckerService.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVAddNewFeatureTypingFromPartUsageTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVDropFromExplorerTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVEdgeCreationTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeActionFlowCreationTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeAnalysisCreationTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeExtensionCreationTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeInterconnectionCreationTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeRequirementCreationTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeStateTransitionCreationTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeStructureCreationTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVSubNodeTemporalCreationTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/controllers/diagrams/general/view/GVTopNodeCreationTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/imports/MutationInsertTextualSysMLv2DataFetcherTests.java
  backend/application/syson-application/src/test/java/org/eclipse/syson/metamodel/helper/ImplicitSpecializationsTests.java
  backend/application/syson-sysml-import/src/main/java/org/eclipse/syson/sysml/dto/InsertTextualSysMLv2EventHandler.java
  backend/services/syson-services/src/main/java/org/eclipse/syson/services/ToolService.java
  backend/services/syson-sysml-rest-api-services/src/main/java/org/eclipse/syson/sysml/rest/api/SysONProjectDataVersioningRestService.java
  backend/views/syson-diagram-actionflow-view/src/main/java/org/eclipse/syson/diagram/actionflow/view/services/ActionFlowViewCreateService.java
  backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewCreateService.java
  backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewNodeService.java
  backend/views/syson-diagram-common-view/src/main/java/org/eclipse/syson/diagram/common/view/services/ViewToolService.java
  backend/views/syson-diagram-general-view/src/main/java/org/eclipse/syson/diagram/general/view/services/GeneralViewCreateService.java
  backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/services/InterconnectionViewCreateService.java
  backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/services/InterconnectionViewNodeService.java
  backend/views/syson-diagram-interconnection-view/src/main/java/org/eclipse/syson/diagram/interconnection/view/services/InterconnectionViewToolService.java
  backend/views/syson-diagram-interconnection-view/src/test/java/org/eclipse/syson/diagram/interconnection/view/InterconnectionViewCreateServiceTests.java
  backend/views/syson-diagram-statetransition-view/src/main/java/org/eclipse/syson/diagram/statetransition/view/services/StateTransitionViewCreateService.java
  backend/views/syson-tree-explorer-view/src/main/java/org/eclipse/syson/tree/explorer/view/handlers/DropTreeItemHandler.java
  backend/views/syson-tree-explorer-view/src/main/java/org/eclipse/syson/tree/explorer/view/services/SysONDefaultExplorerServices.java
  doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
Labels: pr: to review soon, priority: high

#1031 [1028] Improve SuccessionAsUsage with implicit source
  CHANGELOG.adoc
  backend/application/syson-application/src/test/java/org/eclipse/syson/application/export/ImportExportTests.java
  backend/application/syson-sysml-export/src/main/java/org/eclipse/syson/sysml/export/SysMLElementSerializer.java
  backend/application/syson-sysml-export/src/test/java/org/eclipse/syson/sysml/export/SysMLElementSerializerTest.java
  backend/application/syson-sysml-import/src/main/java/org/eclipse/syson/sysml/ASTTransformer.java
  backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/helper/ImplicitSpecializationSwitch.java
  backend/metamodel/syson-sysml-metamodel/src/main/java/org/eclipse/syson/sysml/impl/FeatureImpl.java
  backend/metamodel/syson-sysml-metamodel/src/test/java/org/eclipse/syson/sysml/impl/SuccessionAsUsageTest.java
  backend/metamodel/syson-sysml-metamodel/src/test/java/org/eclipse/syson/sysml/util/ModelBuilder.java
  doc/content/modules/user-manual/pages/release-notes/2025.4.0.adoc
Labels: pr: to review soon, priority: high

#1067 [enh] Footer displays app version from value extracted from package.json
  frontend/syson/src/extensions/SysONFooter.tsx
  frontend/syson/vite.config.js
Labels: pr: to review soon, priority: high
